DELETE FROM `ACCTG_TRANS_ENTRY`;
DELETE FROM `ACCTG_TRANS_ATTRIBUTE`;
DELETE FROM `ACCTG_TRANS`;
DELETE FROM `PAYMENT_APPLICATION`;
DELETE FROM `PAYMENT_GROUP_MEMBER`;
DELETE FROM `PAYMENT_GROUP`;
DELETE FROM `SUBSCRIPTION_PRODUCT`;
DELETE FROM `FIN_ACCOUNT_TRANS_GROUP_MEMBER`;
DELETE FROM `FIN_ACCOUNT_TRANS_GROUP`;
DELETE FROM `FIN_ACCOUNT_TRANS_ATTRIBUTE`;
DELETE FROM `FIN_ACCNT_TRANS_SEQUENCE`;
DELETE FROM `PAYMENT_ATTRIBUTE`;

DELETE FROM `PAYMENT`;
DELETE FROM `FIN_ACCOUNT_TRANS`;
DELETE FROM `INVOICE_STATUS`;
DELETE FROM `ORDER_ITEM_BILLING`; 
DELETE FROM `BILL_OF_SALE_INVOICE_SEQUENCE`;
DELETE FROM `ORDER_ADJUSTMENT_BILLING`;

DELETE FROM `INVOICE_ITEM`;
DELETE FROM `INVOICE_ROLE`;
DELETE FROM `INVOICE_CONTACT_MECH`;
DELETE FROM `INVOICE_ATTRIBUTE`;
DELETE FROM `INVOICE`;
DELETE FROM `GL_ACCOUNT_HISTORY`;
DELETE FROM `GL_RECONCILIATION`;

DELETE FROM `INVENTORY_TRANSFER_GROUP_MEMBER`;
DELETE FROM `INVENTORY_TRANSFER_GROUP`;
DELETE FROM `INVENTORY_TRANSFER`;

DELETE FROM `SHIPMENT_STATUS`;
DELETE FROM `SHIPMENT_ITEM_BILLING`;
DELETE FROM `ITEM_ISSUANCE`;
DELETE FROM `ORDER_ADJUSTMENT`;
DELETE FROM `ORDER_ITEM_SHIP_GROUP_ASSOC`;
DELETE FROM `ORDER_ITEM_SHIP_GROUP`;
DELETE FROM `ORDER_ITEM_CHANGE`;
DELETE FROM `SHIPMENT_ITEM`;
DELETE FROM `SHIPMENT_RECEIPT_SEQUENCE`;
DELETE FROM `SHIPMENT_RECEIPT_STATUS`;
DELETE FROM `SHIPMENT_RECEIPT`;

DELETE FROM `ORDER_STATUS`;
DELETE FROM `ORDER_ROLE`;
DELETE FROM `ORDER_ITEM_ATTRIBUTE`;
DELETE FROM `ORDER_ITEM`;
DELETE FROM `ORDER_HEADER_NOTE`;
DELETE FROM `PRODUCT_PROMO_USE`;
DELETE FROM `ORDER_ATTRIBUTE`;
DELETE FROM `ORDER_TERM`;
DELETE FROM `ORDER_HEADER_SEQUENCE`;
DELETE FROM `ORDER_HEADER`;

DELETE FROM `REQUIREMENT_CUST_REQUEST`;
DELETE FROM `QUOTE_ITEM`;
DELETE FROM `QUOTE_TERM`;
DELETE FROM `QUOTE_ROLE`;
DELETE FROM `QUOTE_STATUS`;
DELETE FROM `QUOTE`;

DELETE FROM `CUST_REQUEST_ITEM`;
DELETE FROM `CUST_REQUEST_STATUS`;
DELETE FROM `CUST_REQUEST_PARTY`;
DELETE FROM `CUST_REQUEST_NOTE`;
DELETE FROM `CUST_REQUEST`;

DELETE FROM `REQUIREMENT_ROLE`;
DELETE FROM `REQUIREMENT_STATUS`;
DELETE FROM `REQUIREMENT`;

DELETE FROM `CRATE_CAN_ACCOUNT`;
DELETE FROM `RETURN_ITEM`;
DELETE FROM `RETURN_STATUS`;
DELETE FROM `RETURN_HEADER`;
DELETE FROM `SHIPMENT_SEQUENCE`;
DELETE FROM `SHIPMENT`;

DELETE FROM `ITEM_ISSUANCE`;
DELETE FROM `INVENTORY_ITEM_DETAIL`;
DELETE FROM `INVENTORY_ITEM`;

DELETE FROM `EMPL_DAILY_ATTENDANCE_DETAIL`;
DELETE FROM `EMPL_LEAVE_BALANCE_STATUS`;
DELETE FROM `EMPL_LEAVE_STATUS`;
DELETE FROM `EMPL_LEAVE`;
DELETE FROM `EMPL_PUNCH`;
DELETE FROM `EMPL_PUNCH_RAW`;
DELETE FROM `EMPLOYEE_FORM16_DETAIL`;
DELETE FROM `PARTY_DEDUCTION`;
DELETE FROM `PARTY_BENEFIT`;
DELETE FROM `PARTY_QUAL`;
DELETE FROM `LOAN_RECOVERY`;
DELETE FROM `PAYROLL_ATTENDANCE`;
DELETE FROM `PAYROLL_HEADER_ITEM_EC`;
DELETE FROM `PAYROLL_HEADER_ITEM`;
DELETE FROM `PAYROLL_HEADER`;
DELETE FROM `PRODUCT_KEYWORD`;
DELETE FROM `POSTAL_ADDRESS`;
DELETE FROM `FACILITY_COMMISSION`;
DELETE FROM `CONTACT_LIST_COMM_STATUS`;
DELETE FROM `L_M_S_PERIOD_SALES_SUMMARY`;
DELETE FROM `L_M_S_PERIOD_SALES_SUMMARY_DETAIL`;

DELETE FROM `JOB_SANDBOX`;
DELETE FROM `IMAGE_DATA_RESOURCE`;
DELETE FROM `SERVER_HIT`;
DELETE FROM `SERVER_HIT_BIN`;
DELETE FROM `USER_LOGIN_HISTORY`;
DELETE FROM `VISIT`;
DELETE FROM `VISITOR`;
DELETE FROM `API_HIT`;
DELETE FROM `ENTITY_AUDIT_LOG`;
DELETE FROM `ENTITY_SYNC_REMOVE`;
DELETE FROM `RUNTIME_DATA`;
DELETE FROM `VEHICLE_TRIP_STATUS`;

DELETE FROM COST_COMPONENT WHERE WORK_EFFORT_ID IN (SELECT WORK_EFFORT_ID FROM WORK_EFFORT WHERE WORK_EFFORT_TYPE_ID IN ("PROD_ORDER_HEADER","PROD_ORDER_TASK"));
DELETE FROM PRODUCT_ASSOC WHERE ROUTING_WORK_EFFORT_ID IN (SELECT WORK_EFFORT_ID FROM WORK_EFFORT WHERE WORK_EFFORT_TYPE_ID IN ("PROD_ORDER_HEADER","PROD_ORDER_TASK"));
DELETE FROM WORK_EFFORT_ASSOC WHERE WORK_EFFORT_ID_TO IN (SELECT WORK_EFFORT_ID FROM WORK_EFFORT WHERE WORK_EFFORT_TYPE_ID IN ("PROD_ORDER_HEADER","PROD_ORDER_TASK"));
DELETE FROM WORK_EFFORT_GOOD_STANDARD WHERE WORK_EFFORT_ID IN (SELECT WORK_EFFORT_ID FROM WORK_EFFORT WHERE WORK_EFFORT_TYPE_ID IN ("PROD_ORDER_HEADER","PROD_ORDER_TASK"));
DELETE FROM WORK_EFFORT WHERE WORK_EFFORT_TYPE_ID IN ("PROD_ORDER_HEADER","PROD_ORDER_TASK");
