-- This script can be used to reset all accounting-related transaction data (invoices, payments, accounting
-- transactions, etc).  This script will need to be enhanced as and when more modules come online.
-- The end result from running this script should result in a fresh database with no accounting-related
-- transaction data and a zero balance sheet.
--
-- The main use of this script to reset all accounting-related data after testing and prior to going live.
-- Hence, even all visit/login data will be purged to have a clean slate.

-- USE `vbiz_VST`;

-- SET AUTOCOMMIT=0;
-- START TRANSACTION;

DELETE FROM `SERVER_HIT`;
DELETE FROM `SERVER_HIT_BIN`;
DELETE FROM `USER_LOGIN_HISTORY`;
DELETE FROM `VISIT`;
DELETE FROM `VISITOR`;
-- DELETE FROM `NOTE_DATA`;

DELETE FROM `GL_RECONCILIATION_ENTRY`;


DELETE FROM `GL_ACCOUNT_HISTORY`;
UPDATE `GL_ACCOUNT` SET `POSTED_BALANCE`=0;
UPDATE `GL_ACCOUNT_ORGANIZATION` SET `POSTED_BALANCE`=0;

DELETE FROM `ACCTG_TRANS_ENTRY`;
DELETE FROM `ACCTG_TRANS_ATTRIBUTE`;
DELETE FROM `ACCTG_TRANS`;
-- DELETE FROM `ACCTG_FORMULA`;
-- DELETE FROM `ACCTG_FORMULA_SLABS`;

UPDATE `CUSTOM_TIME_PERIOD` SET `IS_CLOSED`='N';

DELETE FROM `SHIPMENT_PACKAGE_ROUTE_SEG`;
DELETE FROM `SHIPMENT_ROUTE_SEGMENT`;
DELETE FROM `SHIPMENT_PACKAGE_CONTENT`;
DELETE FROM `SHIPMENT_PACKAGE`;
DELETE FROM `SHIPMENT_STATUS`;
DELETE FROM `SHIPMENT_ITEM_BILLING`;
DELETE FROM `INVENTORY_ITEM_DETAIL`;
DELETE FROM `ITEM_ISSUANCE_ROLE`;
DELETE FROM `ORDER_ITEM_BILLING`;
DELETE FROM `ITEM_ISSUANCE`;
DELETE FROM `ORDER_ADJUSTMENT_BILLING`;
DELETE FROM `ORDER_ADJUSTMENT`;
DELETE FROM `ORDER_CONTACT_MECH`;
DELETE FROM `ORDER_ITEM_SHIP_GROUP_ASSOC`;
DELETE FROM `ORDER_ITEM_SHIP_GROUP`;
DELETE FROM `ORDER_ITEM_PRICE_INFO`;
DELETE FROM `ORDER_ITEM_CHANGE`;
DELETE FROM `ORDER_ITEM_PRICE_INFO`;
DELETE FROM `ORDER_PAYMENT_PREFERENCE`;
DELETE FROM `ORDER_SHIPMENT`;
DELETE FROM `SHIPMENT_ITEM`;
DELETE FROM `SHIPMENT_RECEIPT`;

DELETE FROM `ORDER_STATUS`;
DELETE FROM `ORDER_ROLE`;
DELETE FROM `ORDER_ITEM`;
DELETE FROM `ORDER_HEADER_NOTE`;
SET foreign_key_checks = 0;
DELETE FROM `ORDER_HEADER`;
DELETE FROM `SHIPMENT`;
SET foreign_key_checks = 1;

DELETE FROM `PAYMENT_APPLICATION`;
DELETE FROM `PAYMENT_GROUP_MEMBER`;
DELETE FROM `PAYMENT_GROUP`;

SET foreign_key_checks = 0;
DELETE FROM `PAYMENT`;
DELETE FROM `FIN_ACCOUNT_TRANS`;
SET foreign_key_checks = 1;
-- UPDATE `FIN_ACCOUNT` SET `ACTUAL_BALANCE`=0 ,`AVAILABLE_BALANCE`=0;
-- DELETE FROM `FIN_ACCOUNT` WHERE `FIN_ACCOUNT_TYPE_ID` == 'BANK_ACCOUNT';
DELETE FROM `GL_RECONCILIATION`;

UPDATE `TIME_ENTRY` SET `INVOICE_ID`=NULL ,`INVOICE_ITEM_SEQ_ID`=NULL;

DELETE FROM `INVOICE_STATUS`;
DELETE FROM `INVOICE_ITEM_ASSOC`;

SET foreign_key_checks = 0;
DELETE FROM `INVOICE_ITEM`;
SET foreign_key_checks = 1;

DELETE FROM `INVOICE_CONTACT_MECH`;
DELETE FROM `INVOICE_ROLE`;
DELETE FROM `INVOICE_ATTRIBUTE`;
DELETE FROM `INVOICE`;

DELETE FROM `MILK_CARD_ORDER_ITEM`;
DELETE FROM `MILK_CARD_ORDER`;
DELETE FROM `MILK_CARD_TOTAL`;
DELETE FROM `MILK_CARD_PRODUCT_MAP`;
DELETE FROM `MILK_CARD_TYPE`;
DELETE FROM `CRATES_CANS_ACCNT`;
DELETE FROM `L_M_S_SALES_HISTORY_SUMMARY`;
DELETE FROM `L_M_S_SALES_HISTORY_SUMMARY_DETAIL`;
DELETE FROM `BANK_REMITTANCE`;

-- Facility and party Cleanup



DELETE FROM `EMPL_PUNCH`;
DELETE FROM `EMPL_LEAVE`;
DELETE FROM `EMPL_POSITION_RESPONSIBILITY`;
DELETE FROM `EMPL_POSITION_FULFILLMENT`;
DELETE FROM `EMPL_POSITION`;
DELETE FROM `PARTY_BENEFIT`;
DELETE FROM `PAYROLL_PREFERENCE`;
DELETE FROM `PAY_HISTORY`;
DELETE FROM `EMPLOYMENT`;

DELETE FROM `WORK_EFFORT_ATTRIBUTE`;
DELETE FROM `WORK_EFFORT_GOOD_STANDARD`;
DELETE FROM `WORK_EFFORT_INVENTORY_ASSIGN`;
DELETE FROM `WORK_EFFORT_INVENTORY_PRODUCED`;
DELETE FROM `WORK_EFFORT_FIXED_ASSET_ASSIGN`;
DELETE FROM `WORK_EFFORT_KEYWORD`;
DELETE FROM `WORK_EFFORT_ASSOC`;
DELETE FROM `WORK_EFFORT_STATUS`;
SET foreign_key_checks = 0;
DELETE FROM `WORK_EFFORT`;
SET foreign_key_checks = 1;

DELETE FROM `QUOTE_ADJUSTMENT`;
DELETE FROM `QUOTE_WORK_EFFORT`;
DELETE FROM `QUOTE_TERM`;
DELETE FROM `QUOTE_ATTRIBUTE`;
DELETE FROM `QUOTE_ITEM`;
DELETE FROM `QUOTE_ROLE`;
DELETE FROM `QUOTE`;
DELETE FROM `SUPPLIER_PRODUCT`;
DELETE FROM `REQUIREMENT_ROLE`;

DELETE FROM `SHOPPING_LIST_ITEM`;
DELETE FROM `SHOPPING_LIST`;


DELETE FROM `TIME_ENTRY`;
DELETE FROM `TIMESHEET`;
DELETE FROM `INVENTORY_TRANSFER`;
DELETE FROM `INVENTORY_ITEM`;

DELETE FROM `CUST_REQUEST_ITEM`;
DELETE FROM `CUST_REQUEST_STATUS`;
DELETE FROM `CUST_REQUEST_PARTY`;
DELETE FROM `CUST_REQUEST`;
DELETE FROM `FIXED_ASSET_STD_COST`;
DELETE FROM `FIXED_ASSET`;
DELETE FROM `MRP_EVENT`;
DELETE FROM `REQUIREMENT`;


-- Product cleanup
/*
DELETE FROM `PRODUCT_STORE_SHIPMENT_METH`;
DELETE FROM `PRODUCT_STORE_FACILITY`;
DELETE FROM `PRODUCT_STORE_CATALOG`;
DELETE FROM `PRODUCT_STORE`;
DELETE FROM `PROD_CATALOG_CATEGORY`;
DELETE FROM `PROD_CATALOG`;
DELETE FROM `PRODUCT_PRICE_CHANGE`;
DELETE FROM `PRODUCT_PRICE`;
DELETE FROM `PRODUCT_KEYWORD`;
DELETE FROM `PRODUCT_FACILITY`;
DELETE FROM `PRODUCT_ASSOC`;
DELETE FROM `PRODUCT_CALCULATED_INFO`;
DELETE FROM `PRODUCT_CATEGORY_MEMBER`;
DELETE FROM `PRODUCT_ATTRIBUTE`;
DELETE FROM `PRODUCT_AVERAGE_COST`;
DELETE FROM `PRODUCT_GL_ACCOUNT`;
DELETE FROM `PRODUCT_PAYMENT_METHOD_TYPE`;
DELETE FROM `PRODUCT`;
DELETE FROM `PRODUCT_CATEGORY`;
DELETE FROM `PRODUCT_FEATURE_APPL`; */
DELETE FROM `PRODUCT_PRICE_CHANGE`;

DELETE FROM `GL_ACCOUNT_ORGANIZATION` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `GL_ACCOUNT_TYPE_DEFAULT` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PARTY_ACCTG_PREFERENCE` WHERE `PARTY_ID` <> 'Company';
DELETE FROM `GL_JOURNAL` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PAYMENT_METHOD_TYPE_GL_ACCOUNT` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PAYMENT_GL_ACCOUNT_TYPE_MAP` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';


DELETE FROM BILLING_ACCOUNT_ROLE;
DELETE FROM FACILITY_PARTY;

DELETE FROM `PARTY_NAME_HISTORY`;
DELETE FROM `COMMUNICATION_EVENT_ROLE`;
DELETE FROM `COMMUNICATION_EVENT`;
DELETE FROM `FACILITY_CONTACT_MECH_PURPOSE`;
DELETE FROM `FACILITY_CONTACT_MECH`;
DELETE FROM `FACILITY_PARTY`;
DELETE FROM `FACILITY_CONTENT`;
SET foreign_key_checks = 0;
DELETE FROM `FACILITY`;
SET foreign_key_checks = 1;
DELETE FROM `PARTY_CONTACT_MECH`;
DELETE FROM `PARTY_CONTACT_MECH_PURPOSE`;
DELETE FROM `POSTAL_ADDRESS`;
DELETE FROM `TELECOM_NUMBER`;
DELETE FROM `CONTACT_MECH`;
DELETE FROM `PARTY_CLASSIFICATION`;
DELETE FROM `PARTY_CLASSIFICATION_GROUP`;
DELETE FROM `PARTY_GL_ACCOUNT`;
DELETE FROM `PARTY_RELATIONSHIP`;
DELETE FROM `DATA_RESOURCE_ROLE`;
DELETE FROM `PARTY_ROLE` WHERE `PARTY_ID` <> 'Company' AND `PARTY_ID` <> '_NA_' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` NOT LIKE 'TAX%' ;
DELETE FROM `PARTY_STATUS` WHERE `PARTY_ID` <> 'Company';

DELETE FROM `PARTY_GROUP` WHERE `PARTY_ID` <> 'Company' AND `PARTY_ID` NOT LIKE 'TAX%';
DELETE FROM `PERSON` WHERE `PARTY_ID` <> '306' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` <> 'system' AND `PARTY_ID` <> '_NA_';


DELETE FROM `USER_LOGIN_SECURITY_GROUP` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> 'system';
DELETE FROM `USER_PREFERENCE` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> '_NA_';

SET foreign_key_checks = 0;
DELETE FROM `PARTY` WHERE `PARTY_ID` <> '1001' AND `PARTY_ID` <> 'Company' AND `PARTY_ID` NOT LIKE 'TAX%' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` <> 'system' AND `PARTY_ID` <> '_NA_';
DELETE FROM `USER_LOGIN` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> 'system' AND `USER_LOGIN_ID` <> 'anonymous';
SET foreign_key_checks = 1;

DELETE FROM `ABSENTEE_OVERRIDE`;
DELETE FROM `SUBSCRIPTION_PRODUCT`;
DELETE FROM `SUBSCRIPTION`;

-- COMMIT;
