
DELETE FROM `EMPL_PUNCH`;
DELETE FROM `EMPL_LEAVE`;
DELETE FROM `EMPL_POSITION_RESPONSIBILITY`;
DELETE FROM `EMPL_POSITION_FULFILLMENT`;
DELETE FROM `EMPL_POSITION`;
DELETE FROM `PARTY_BENEFIT`;
DELETE FROM `PAYROLL_PREFERENCE`;
DELETE FROM `PAY_HISTORY`;
DELETE FROM `EMPLOYMENT`;

DELETE FROM `WORK_EFFORT_ATTRIBUTE`;
DELETE FROM `WORK_EFFORT_GOOD_STANDARD`;
DELETE FROM `WORK_EFFORT_INVENTORY_ASSIGN`;
DELETE FROM `WORK_EFFORT_INVENTORY_PRODUCED`;
DELETE FROM `WORK_EFFORT_FIXED_ASSET_ASSIGN`;
DELETE FROM `WORK_EFFORT_KEYWORD`;
DELETE FROM `WORK_EFFORT_ASSOC`;
DELETE FROM `WORK_EFFORT_STATUS`;
SET foreign_key_checks = 0;
DELETE FROM `WORK_EFFORT`;
SET foreign_key_checks = 1;

DELETE FROM `QUOTE_ADJUSTMENT`;
DELETE FROM `QUOTE_WORK_EFFORT`;
DELETE FROM `QUOTE_TERM`;
DELETE FROM `QUOTE_ATTRIBUTE`;
DELETE FROM `QUOTE_ITEM`;
DELETE FROM `QUOTE_ROLE`;
DELETE FROM `QUOTE`;
DELETE FROM `SUPPLIER_PRODUCT`;
DELETE FROM `REQUIREMENT_ROLE`;

DELETE FROM `SHOPPING_LIST_ITEM`;
DELETE FROM `SHOPPING_LIST`;


DELETE FROM `TIME_ENTRY`;
DELETE FROM `TIMESHEET`;
DELETE FROM `INVENTORY_TRANSFER`;
DELETE FROM `INVENTORY_ITEM`;

DELETE FROM `CUST_REQUEST_ITEM`;
DELETE FROM `CUST_REQUEST_STATUS`;
DELETE FROM `CUST_REQUEST_PARTY`;
DELETE FROM `CUST_REQUEST`;
DELETE FROM `FIXED_ASSET_STD_COST`;
DELETE FROM `FIXED_ASSET`;
DELETE FROM `MRP_EVENT`;
DELETE FROM `REQUIREMENT`;
DELETE FROM `PRODUCT_STORE_SHIPMENT_METH`;
DELETE FROM `PRODUCT_STORE_FACILITY`;
DELETE FROM `PRODUCT_STORE_CATALOG`;
DELETE FROM `PRODUCT_STORE`;
DELETE FROM `PROD_CATALOG_CATEGORY`;
DELETE FROM `PROD_CATALOG`;
DELETE FROM `PRODUCT_PRICE_CHANGE`;
DELETE FROM `PRODUCT_PRICE`;
DELETE FROM `PRODUCT_KEYWORD`;
DELETE FROM `PRODUCT_FACILITY`;
DELETE FROM `PRODUCT_ASSOC`;
DELETE FROM `PRODUCT_CALCULATED_INFO`;
DELETE FROM `PRODUCT_CATEGORY_MEMBER`;
DELETE FROM `PRODUCT_ATTRIBUTE`;
DELETE FROM `PRODUCT_AVERAGE_COST`;
DELETE FROM `PRODUCT_GL_ACCOUNT`;
DELETE FROM `PRODUCT_PAYMENT_METHOD_TYPE`;
DELETE FROM `PRODUCT`;
DELETE FROM `PRODUCT_CATEGORY`;


DELETE FROM `GL_ACCOUNT_ORGANIZATION` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `GL_ACCOUNT_TYPE_DEFAULT` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PARTY_ACCTG_PREFERENCE` WHERE `PARTY_ID` <> 'Company';
DELETE FROM `GL_JOURNAL` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PAYMENT_METHOD_TYPE_GL_ACCOUNT` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';
DELETE FROM `PAYMENT_GL_ACCOUNT_TYPE_MAP` WHERE `ORGANIZATION_PARTY_ID` <> 'Company';


DELETE FROM BILLING_ACCOUNT_ROLE;
DELETE FROM FACILITY_PARTY;
DELETE FROM FACILITY_RATE;

DELETE FROM `PARTY_NAME_HISTORY`;
DELETE FROM `COMMUNICATION_EVENT_ROLE`;
DELETE FROM `COMMUNICATION_EVENT`;
DELETE FROM `FACILITY_CONTACT_MECH_PURPOSE`;
DELETE FROM `FACILITY_CONTACT_MECH`;
DELETE FROM FACILITY_PARTY;
SET foreign_key_checks = 0;
DELETE FROM FACILITY;
SET foreign_key_checks = 1;
DELETE FROM `PARTY_CONTACT_MECH`;
DELETE FROM `PARTY_CONTACT_MECH_PURPOSE`;
DELETE FROM `POSTAL_ADDRESS`;
DELETE FROM `TELECOM_NUMBER`;
DELETE FROM `CONTACT_MECH`;
DELETE FROM `PARTY_CLASSIFICATION`;
DELETE FROM `PARTY_CLASSIFICATION_GROUP`;
DELETE FROM `PARTY_GL_ACCOUNT`;
DELETE FROM `PARTY_RELATIONSHIP`;
DELETE FROM `DATA_RESOURCE_ROLE`;
DELETE FROM `PARTY_ROLE` WHERE `PARTY_ID` <> 'Company' AND `PARTY_ID` <> '_NA_' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` NOT LIKE 'TAX%' ;
DELETE FROM `PARTY_STATUS` WHERE `PARTY_ID` <> 'Company';

DELETE FROM `PARTY_GROUP` WHERE `PARTY_ID` <> 'Company' AND `PARTY_ID` NOT LIKE 'TAX%';
DELETE FROM `PERSON` WHERE `PARTY_ID` <> '306' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` <> 'system' AND `PARTY_ID` <> '_NA_';


DELETE FROM `USER_LOGIN_SECURITY_GROUP` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> 'system';
DELETE FROM `USER_PREFERENCE` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> '_NA_';

SET foreign_key_checks = 0;
DELETE FROM `PARTY` WHERE `PARTY_ID` <> '306' AND `PARTY_ID` <> 'Company' AND `PARTY_ID` NOT LIKE 'TAX%' AND `PARTY_ID` <> 'PETTY_VENDOR' AND `PARTY_ID` <> 'system' AND `PARTY_ID` <> '_NA_';
DELETE FROM `USER_LOGIN` WHERE `USER_LOGIN_ID` <> 'kvarma' AND `USER_LOGIN_ID` <> 'system' AND `USER_LOGIN_ID` <> 'anonymous';
SET foreign_key_checks = 1;
DELETE  FROM `FIN_ACCOUNT_STATUS`;
DELETE  FROM `FIN_ACCOUNT` WHERE `FIN_ACCOUNT_CODE` NOT IN ("CST_CREDIT","EXCISE_CREDIT","FIN_ACCNT1","FIN_ACCNT2","FIN_ACCNT3","INPUT_VAT_CREDIT","PETTY_CASH","SERVICE_TAX_CREDIT","TDS_CREDIT");

