-- this script is used to clean the Procurement related Data

 		
DELETE FROM ORDER_ITEM_BILLING WHERE ORDER_ID IN (SELECT ORDER_ID FROM  ORDER_HEADER WHERE PURPOSE_TYPE_ID ="MILK_PROCUREMENT" AND ORDER_TYPE_ID = "PURCHASE_ORDER"); 		
DELETE  FROM INVOICE_STATUS WHERE INVOICE_ID IN (SELECT INVOICE_ID FROM INVOICE WHERE  REFERENCE_NUMBER LIKE "PROC_BILLING_%");
DELETE  FROM INVOICE_ITEM   WHERE INVOICE_ID IN (SELECT INVOICE_ID FROM INVOICE WHERE  REFERENCE_NUMBER LIKE "PROC_BILLING_%");
DELETE FROM INVOICE WHERE REFERENCE_NUMBER LIKE "PROC_BILLING_%";
DELETE FROM ORDER_ITEM WHERE ORDER_ID IN (SELECT ORDER_ID FROM  ORDER_HEADER WHERE PURPOSE_TYPE_ID ="MILK_PROCUREMENT" AND ORDER_TYPE_ID = "PURCHASE_ORDER");
DELETE FROM ORDER_STATUS WHERE ORDER_ID IN (SELECT ORDER_ID FROM  ORDER_HEADER WHERE PURPOSE_TYPE_ID ="MILK_PROCUREMENT" AND ORDER_TYPE_ID = "PURCHASE_ORDER");
DELETE FROM ORDER_ROLE WHERE ORDER_ID IN (SELECT ORDER_ID FROM  ORDER_HEADER WHERE PURPOSE_TYPE_ID ="MILK_PROCUREMENT" AND ORDER_TYPE_ID = "PURCHASE_ORDER");    
DELETE FROM  ORDER_HEADER WHERE PURPOSE_TYPE_ID ="MILK_PROCUREMENT" AND ORDER_TYPE_ID = "PURCHASE_ORDER" ;   
DELETE FROM PERIOD_BILLING WHERE BILLING_TYPE_ID ="PB_PROC_MRGN";
