--
--  This script will wipe out all transactional data (accounting, hr, sales/marketing) 
--  from the database.
--  
--
-- WARNING: Be absolutely sure you know what you're doing before running this script.
--
--

SET foreign_key_checks = 0;

--
-- Visits/Audit cleanup
--

CREATE TABLE NEW_SERVER_HIT LIKE SERVER_HIT;
RENAME TABLE SERVER_HIT TO OLD_SERVER_HIT, NEW_SERVER_HIT to SERVER_HIT;
DROP TABLE OLD_SERVER_HIT;

CREATE TABLE NEW_SERVER_HIT_BIN LIKE SERVER_HIT_BIN;
RENAME TABLE SERVER_HIT_BIN TO OLD_SERVER_HIT_BIN, NEW_SERVER_HIT_BIN to SERVER_HIT_BIN;
DROP TABLE OLD_SERVER_HIT_BIN;

CREATE TABLE NEW_USER_LOGIN_HISTORY LIKE USER_LOGIN_HISTORY;
RENAME TABLE USER_LOGIN_HISTORY TO OLD_USER_LOGIN_HISTORY, NEW_USER_LOGIN_HISTORY to USER_LOGIN_HISTORY;
DROP TABLE OLD_USER_LOGIN_HISTORY;

CREATE TABLE NEW_VISIT LIKE VISIT;
RENAME TABLE VISIT TO OLD_VISIT, NEW_VISIT to VISIT;
DROP TABLE OLD_VISIT;

CREATE TABLE NEW_VISITOR LIKE VISITOR;
RENAME TABLE VISITOR TO OLD_VISITOR, NEW_VISITOR to VISITOR;
DROP TABLE OLD_VISITOR;

CREATE TABLE NEW_ENTITY_AUDIT_LOG LIKE ENTITY_AUDIT_LOG;
RENAME TABLE ENTITY_AUDIT_LOG TO OLD_ENTITY_AUDIT_LOG, NEW_ENTITY_AUDIT_LOG to ENTITY_AUDIT_LOG;
DROP TABLE OLD_ENTITY_AUDIT_LOG;

CREATE TABLE NEW_ENTITY_SYNC_REMOVE LIKE ENTITY_SYNC_REMOVE;
RENAME TABLE ENTITY_SYNC_REMOVE TO OLD_ENTITY_SYNC_REMOVE, NEW_ENTITY_SYNC_REMOVE to ENTITY_SYNC_REMOVE;
DROP TABLE OLD_ENTITY_SYNC_REMOVE;  

--
--  Accounting transaction cleanup
--

UPDATE `FIN_ACCOUNT_TRANS` SET `GL_RECONCILIATION_ID`=NULL;
DELETE FROM `GL_RECONCILIATION_ENTRY`;

DELETE FROM `GL_RECONCILIATION`;

DELETE FROM `GL_ACCOUNT_HISTORY`;
UPDATE `GL_ACCOUNT` SET `POSTED_BALANCE`=0;
UPDATE `GL_ACCOUNT_ORGANIZATION` SET `POSTED_BALANCE`=0;

UPDATE `FIN_ACCOUNT` SET `ACTUAL_BALANCE`=0 ,`AVAILABLE_BALANCE`=0;

CREATE TABLE NEW_ENTITY_SYNC_REMOVE LIKE ENTITY_SYNC_REMOVE;
RENAME TABLE ENTITY_SYNC_REMOVE TO OLD_ENTITY_SYNC_REMOVE, NEW_ENTITY_SYNC_REMOVE to ENTITY_SYNC_REMOVE;
DROP TABLE OLD_ENTITY_SYNC_REMOVE;

SET foreign_key_checks = 0;
CREATE TABLE NEW_ACCTG_TRANS_ENTRY LIKE ACCTG_TRANS_ENTRY;
RENAME TABLE ACCTG_TRANS_ENTRY TO OLD_ACCTG_TRANS_ENTRY, NEW_ACCTG_TRANS_ENTRY to ACCTG_TRANS_ENTRY;
DROP TABLE OLD_ACCTG_TRANS_ENTRY;
SET foreign_key_checks = 1;

CREATE TABLE NEW_ACCTG_TRANS_ATTRIBUTE LIKE ACCTG_TRANS_ATTRIBUTE;
RENAME TABLE ACCTG_TRANS_ATTRIBUTE TO OLD_ACCTG_TRANS_ATTRIBUTE, NEW_ACCTG_TRANS_ATTRIBUTE to ACCTG_TRANS_ATTRIBUTE;
DROP TABLE OLD_ACCTG_TRANS_ATTRIBUTE;

CREATE TABLE NEW_ACCTG_TRANS LIKE ACCTG_TRANS;
RENAME TABLE ACCTG_TRANS TO OLD_ACCTG_TRANS, NEW_ACCTG_TRANS to ACCTG_TRANS;
DROP TABLE OLD_ACCTG_TRANS;

--
-- Rest of the transactions cleanup
--

CREATE TABLE NEW_API_HIT LIKE API_HIT;
RENAME TABLE API_HIT TO OLD_API_HIT, NEW_API_HIT to API_HIT;
DROP TABLE OLD_API_HIT;

CREATE TABLE NEW_BILL_OF_SALE_INVOICE_SEQUENCE LIKE BILL_OF_SALE_INVOICE_SEQUENCE;
RENAME TABLE BILL_OF_SALE_INVOICE_SEQUENCE TO OLD_BILL_OF_SALE_INVOICE_SEQUENCE, NEW_BILL_OF_SALE_INVOICE_SEQUENCE to BILL_OF_SALE_INVOICE_SEQUENCE;
DROP TABLE OLD_BILL_OF_SALE_INVOICE_SEQUENCE;

CREATE TABLE NEW_CRATE_CAN_ACCOUNT LIKE CRATE_CAN_ACCOUNT;
RENAME TABLE CRATE_CAN_ACCOUNT TO OLD_CRATE_CAN_ACCOUNT, NEW_CRATE_CAN_ACCOUNT to CRATE_CAN_ACCOUNT;
DROP TABLE OLD_CRATE_CAN_ACCOUNT;

CREATE TABLE NEW_DAILYINDENTDETAIL LIKE DAILYINDENTDETAIL;
RENAME TABLE DAILYINDENTDETAIL TO OLD_DAILYINDENTDETAIL, NEW_DAILYINDENTDETAIL to DAILYINDENTDETAIL;
DROP TABLE OLD_DAILYINDENTDETAIL;

CREATE TABLE NEW_DAILYINDENT LIKE DAILYINDENT;
RENAME TABLE DAILYINDENT TO OLD_DAILYINDENT, NEW_DAILYINDENT to DAILYINDENT;
DROP TABLE OLD_DAILYINDENT;

CREATE TABLE NEW_EMPL_DAILY_ATTENDANCE_DETAIL LIKE EMPL_DAILY_ATTENDANCE_DETAIL;
RENAME TABLE EMPL_DAILY_ATTENDANCE_DETAIL TO OLD_EMPL_DAILY_ATTENDANCE_DETAIL, NEW_EMPL_DAILY_ATTENDANCE_DETAIL to EMPL_DAILY_ATTENDANCE_DETAIL;
DROP TABLE OLD_EMPL_DAILY_ATTENDANCE_DETAIL;

CREATE TABLE NEW_EMPL_LEAVE_STATUS LIKE EMPL_LEAVE_STATUS;
RENAME TABLE EMPL_LEAVE_STATUS TO OLD_EMPL_LEAVE_STATUS, NEW_EMPL_LEAVE_STATUS to EMPL_LEAVE_STATUS;
DROP TABLE OLD_EMPL_LEAVE_STATUS;

CREATE TABLE NEW_EMPL_LEAVE LIKE EMPL_LEAVE;
RENAME TABLE EMPL_LEAVE TO OLD_EMPL_LEAVE, NEW_EMPL_LEAVE to EMPL_LEAVE;
DROP TABLE OLD_EMPL_LEAVE;

CREATE TABLE NEW_EMPL_LEAVE_BALANCE_STATUS LIKE EMPL_LEAVE_BALANCE_STATUS;
RENAME TABLE EMPL_LEAVE_BALANCE_STATUS TO OLD_EMPL_LEAVE_BALANCE_STATUS, NEW_EMPL_LEAVE_BALANCE_STATUS to EMPL_LEAVE_BALANCE_STATUS;
DROP TABLE OLD_EMPL_LEAVE_BALANCE_STATUS;

CREATE TABLE NEW_EMPL_PUNCH_RAW LIKE EMPL_PUNCH_RAW;
RENAME TABLE EMPL_PUNCH_RAW TO OLD_EMPL_PUNCH_RAW, NEW_EMPL_PUNCH_RAW to EMPL_PUNCH_RAW;
DROP TABLE OLD_EMPL_PUNCH_RAW;

CREATE TABLE NEW_EMPL_PUNCH LIKE EMPL_PUNCH;
RENAME TABLE EMPL_PUNCH TO OLD_EMPL_PUNCH, NEW_EMPL_PUNCH to EMPL_PUNCH;
DROP TABLE OLD_EMPL_PUNCH;

CREATE TABLE NEW_FACILITY_COMMISSION LIKE FACILITY_COMMISSION;
RENAME TABLE FACILITY_COMMISSION TO OLD_FACILITY_COMMISSION, NEW_FACILITY_COMMISSION to FACILITY_COMMISSION;
DROP TABLE OLD_FACILITY_COMMISSION;

CREATE TABLE NEW_FIN_ACCNT_TRANS_SEQUENCE LIKE FIN_ACCNT_TRANS_SEQUENCE;
RENAME TABLE FIN_ACCNT_TRANS_SEQUENCE TO OLD_FIN_ACCNT_TRANS_SEQUENCE, NEW_FIN_ACCNT_TRANS_SEQUENCE to FIN_ACCNT_TRANS_SEQUENCE;
DROP TABLE OLD_FIN_ACCNT_TRANS_SEQUENCE;

CREATE TABLE NEW_FIN_ACCOUNT_TRANS_ATTRIBUTE LIKE FIN_ACCOUNT_TRANS_ATTRIBUTE;
RENAME TABLE FIN_ACCOUNT_TRANS_ATTRIBUTE TO OLD_FIN_ACCOUNT_TRANS_ATTRIBUTE, NEW_FIN_ACCOUNT_TRANS_ATTRIBUTE to FIN_ACCOUNT_TRANS_ATTRIBUTE;
DROP TABLE OLD_FIN_ACCOUNT_TRANS_ATTRIBUTE;

CREATE TABLE NEW_FIN_ACCOUNT_TRANS LIKE FIN_ACCOUNT_TRANS;
RENAME TABLE FIN_ACCOUNT_TRANS TO OLD_FIN_ACCOUNT_TRANS, NEW_FIN_ACCOUNT_TRANS to FIN_ACCOUNT_TRANS;
DROP TABLE OLD_FIN_ACCOUNT_TRANS;

CREATE TABLE NEW_IMAGE_DATA_RESOURCE LIKE IMAGE_DATA_RESOURCE;
RENAME TABLE IMAGE_DATA_RESOURCE TO OLD_IMAGE_DATA_RESOURCE, NEW_IMAGE_DATA_RESOURCE to IMAGE_DATA_RESOURCE;
DROP TABLE OLD_IMAGE_DATA_RESOURCE;

CREATE TABLE NEW_INVOICE_STATUS LIKE INVOICE_STATUS;
RENAME TABLE INVOICE_STATUS TO OLD_INVOICE_STATUS, NEW_INVOICE_STATUS to INVOICE_STATUS;
DROP TABLE OLD_INVOICE_STATUS;

CREATE TABLE NEW_INVOICE_ITEM LIKE INVOICE_ITEM;
RENAME TABLE INVOICE_ITEM TO OLD_INVOICE_ITEM, NEW_INVOICE_ITEM to INVOICE_ITEM;
DROP TABLE OLD_INVOICE_ITEM;

CREATE TABLE NEW_INVOICE_ATTRIBUTE LIKE INVOICE_ATTRIBUTE;
RENAME TABLE INVOICE_ATTRIBUTE TO OLD_INVOICE_ATTRIBUTE, NEW_INVOICE_ATTRIBUTE to INVOICE_ATTRIBUTE;
DROP TABLE OLD_INVOICE_ATTRIBUTE;

CREATE TABLE NEW_INVOICE_CONTACT_MECH LIKE INVOICE_CONTACT_MECH;
RENAME TABLE INVOICE_CONTACT_MECH TO OLD_INVOICE_CONTACT_MECH, NEW_INVOICE_CONTACT_MECH to INVOICE_CONTACT_MECH;
DROP TABLE OLD_INVOICE_CONTACT_MECH;

CREATE TABLE NEW_INVOICE LIKE INVOICE;
RENAME TABLE INVOICE TO OLD_INVOICE, NEW_INVOICE to INVOICE;
DROP TABLE OLD_INVOICE;

CREATE TABLE NEW_ITEM_ISSUANCE LIKE ITEM_ISSUANCE;
RENAME TABLE ITEM_ISSUANCE TO OLD_ITEM_ISSUANCE, NEW_ITEM_ISSUANCE to ITEM_ISSUANCE;
DROP TABLE OLD_ITEM_ISSUANCE;

CREATE TABLE NEW_JOB_SANDBOX LIKE JOB_SANDBOX;
RENAME TABLE JOB_SANDBOX TO OLD_JOB_SANDBOX, NEW_JOB_SANDBOX to JOB_SANDBOX;
DROP TABLE OLD_JOB_SANDBOX;

CREATE TABLE NEW_LOAN_RECOVERY LIKE LOAN_RECOVERY;
RENAME TABLE LOAN_RECOVERY TO OLD_LOAN_RECOVERY, NEW_LOAN_RECOVERY to LOAN_RECOVERY;
DROP TABLE OLD_LOAN_RECOVERY;

CREATE TABLE NEW_ORDER_ADJUSTMENT_BILLING LIKE ORDER_ADJUSTMENT_BILLING;
RENAME TABLE ORDER_ADJUSTMENT_BILLING TO OLD_ORDER_ADJUSTMENT_BILLING, NEW_ORDER_ADJUSTMENT_BILLING to ORDER_ADJUSTMENT_BILLING;
DROP TABLE OLD_ORDER_ADJUSTMENT_BILLING;

CREATE TABLE NEW_ORDER_ADJUSTMENT LIKE ORDER_ADJUSTMENT;
RENAME TABLE ORDER_ADJUSTMENT TO OLD_ORDER_ADJUSTMENT, NEW_ORDER_ADJUSTMENT to ORDER_ADJUSTMENT;
DROP TABLE OLD_ORDER_ADJUSTMENT;

CREATE TABLE NEW_ORDER_ATTRIBUTE LIKE ORDER_ATTRIBUTE;
RENAME TABLE ORDER_ATTRIBUTE TO OLD_ORDER_ATTRIBUTE, NEW_ORDER_ATTRIBUTE to ORDER_ATTRIBUTE;
DROP TABLE OLD_ORDER_ATTRIBUTE;

CREATE TABLE NEW_ORDER_ITEM_BILLING LIKE ORDER_ITEM_BILLING;
RENAME TABLE ORDER_ITEM_BILLING TO OLD_ORDER_ITEM_BILLING, NEW_ORDER_ITEM_BILLING to ORDER_ITEM_BILLING;
DROP TABLE OLD_ORDER_ITEM_BILLING;

CREATE TABLE NEW_ORDER_ITEM_SHIP_GROUP_ASSOC LIKE ORDER_ITEM_SHIP_GROUP_ASSOC;
RENAME TABLE ORDER_ITEM_SHIP_GROUP_ASSOC TO OLD_ORDER_ITEM_SHIP_GROUP_ASSOC, NEW_ORDER_ITEM_SHIP_GROUP_ASSOC to ORDER_ITEM_SHIP_GROUP_ASSOC;
DROP TABLE OLD_ORDER_ITEM_SHIP_GROUP_ASSOC;

CREATE TABLE NEW_ORDER_ITEM_SHIP_GROUP LIKE ORDER_ITEM_SHIP_GROUP;
RENAME TABLE ORDER_ITEM_SHIP_GROUP TO OLD_ORDER_ITEM_SHIP_GROUP, NEW_ORDER_ITEM_SHIP_GROUP to ORDER_ITEM_SHIP_GROUP;
DROP TABLE OLD_ORDER_ITEM_SHIP_GROUP;

CREATE TABLE NEW_ORDER_ITEM LIKE ORDER_ITEM;
RENAME TABLE ORDER_ITEM TO OLD_ORDER_ITEM, NEW_ORDER_ITEM to ORDER_ITEM;
DROP TABLE OLD_ORDER_ITEM;

CREATE TABLE NEW_ORDER_ROLE LIKE ORDER_ROLE;
RENAME TABLE ORDER_ROLE TO OLD_ORDER_ROLE, NEW_ORDER_ROLE to ORDER_ROLE;
DROP TABLE OLD_ORDER_ROLE;

CREATE TABLE NEW_ORDER_HEADER LIKE ORDER_HEADER;
RENAME TABLE ORDER_HEADER TO OLD_ORDER_HEADER, NEW_ORDER_HEADER to ORDER_HEADER;
DROP TABLE OLD_ORDER_HEADER;

CREATE TABLE NEW_PAYMENT_APPLICATION LIKE PAYMENT_APPLICATION;
RENAME TABLE PAYMENT_APPLICATION TO OLD_PAYMENT_APPLICATION, NEW_PAYMENT_APPLICATION to PAYMENT_APPLICATION;
DROP TABLE OLD_PAYMENT_APPLICATION;

CREATE TABLE NEW_PAYMENT_ATTRIBUTE LIKE PAYMENT_ATTRIBUTE;
RENAME TABLE PAYMENT_ATTRIBUTE TO OLD_PAYMENT_ATTRIBUTE, NEW_PAYMENT_ATTRIBUTE to PAYMENT_ATTRIBUTE;
DROP TABLE OLD_PAYMENT_ATTRIBUTE;

CREATE TABLE NEW_PAYMENT_GROUP_MEMBER LIKE PAYMENT_GROUP_MEMBER;
RENAME TABLE PAYMENT_GROUP_MEMBER TO OLD_PAYMENT_GROUP_MEMBER, NEW_PAYMENT_GROUP_MEMBER to PAYMENT_GROUP_MEMBER;
DROP TABLE OLD_PAYMENT_GROUP_MEMBER;

CREATE TABLE NEW_PAYMENT_GROUP LIKE PAYMENT_GROUP;
RENAME TABLE PAYMENT_GROUP TO OLD_PAYMENT_GROUP, NEW_PAYMENT_GROUP to PAYMENT_GROUP;
DROP TABLE OLD_PAYMENT_GROUP;

CREATE TABLE NEW_PAYMENT LIKE PAYMENT;
RENAME TABLE PAYMENT TO OLD_PAYMENT, NEW_PAYMENT to PAYMENT;
DROP TABLE OLD_PAYMENT;

CREATE TABLE NEW_PAYROLL_ATTENDANCE_SHIFT_WISE LIKE PAYROLL_ATTENDANCE_SHIFT_WISE;
RENAME TABLE PAYROLL_ATTENDANCE_SHIFT_WISE TO OLD_PAYROLL_ATTENDANCE_SHIFT_WISE, NEW_PAYROLL_ATTENDANCE_SHIFT_WISE to PAYROLL_ATTENDANCE_SHIFT_WISE;
DROP TABLE OLD_PAYROLL_ATTENDANCE_SHIFT_WISE;

CREATE TABLE NEW_PAYROLL_ATTENDANCE LIKE PAYROLL_ATTENDANCE;
RENAME TABLE PAYROLL_ATTENDANCE TO OLD_PAYROLL_ATTENDANCE, NEW_PAYROLL_ATTENDANCE to PAYROLL_ATTENDANCE;
DROP TABLE OLD_PAYROLL_ATTENDANCE;

CREATE TABLE NEW_PAYROLL_HEADER_ITEM LIKE PAYROLL_HEADER_ITEM;
RENAME TABLE PAYROLL_HEADER_ITEM TO OLD_PAYROLL_HEADER_ITEM, NEW_PAYROLL_HEADER_ITEM to PAYROLL_HEADER_ITEM;
DROP TABLE OLD_PAYROLL_HEADER_ITEM;

CREATE TABLE NEW_PAYROLL_HEADER LIKE PAYROLL_HEADER;
RENAME TABLE PAYROLL_HEADER TO OLD_PAYROLL_HEADER, NEW_PAYROLL_HEADER to PAYROLL_HEADER;
DROP TABLE OLD_PAYROLL_HEADER;

CREATE TABLE NEW_RETURN_STATUS LIKE RETURN_STATUS;
RENAME TABLE RETURN_STATUS TO OLD_RETURN_STATUS, NEW_RETURN_STATUS to RETURN_STATUS;
DROP TABLE OLD_RETURN_STATUS;

CREATE TABLE NEW_RETURN_REASON LIKE RETURN_REASON;
RENAME TABLE RETURN_REASON TO OLD_RETURN_REASON, NEW_RETURN_REASON to RETURN_REASON;
DROP TABLE OLD_RETURN_REASON;

CREATE TABLE NEW_RETURN_ITEM LIKE RETURN_ITEM;
RENAME TABLE RETURN_ITEM TO OLD_RETURN_ITEM, NEW_RETURN_ITEM to RETURN_ITEM;
DROP TABLE OLD_RETURN_ITEM;

CREATE TABLE NEW_RETURN_HEADER LIKE RETURN_HEADER;
RENAME TABLE RETURN_HEADER TO OLD_RETURN_HEADER, NEW_RETURN_HEADER to RETURN_HEADER;
DROP TABLE OLD_RETURN_HEADER;

CREATE TABLE NEW_RUNTIME_DATA LIKE RUNTIME_DATA;
RENAME TABLE RUNTIME_DATA TO OLD_RUNTIME_DATA, NEW_RUNTIME_DATA to RUNTIME_DATA;
DROP TABLE OLD_RUNTIME_DATA;

CREATE TABLE NEW_SHIPMENT LIKE SHIPMENT;
RENAME TABLE SHIPMENT TO OLD_SHIPMENT, NEW_SHIPMENT to SHIPMENT;
DROP TABLE OLD_SHIPMENT;

CREATE TABLE NEW_SUBSCRIPTION_PRODUCT LIKE SUBSCRIPTION_PRODUCT;
RENAME TABLE SUBSCRIPTION_PRODUCT TO OLD_SUBSCRIPTION_PRODUCT, NEW_SUBSCRIPTION_PRODUCT to SUBSCRIPTION_PRODUCT;
DROP TABLE OLD_SUBSCRIPTION_PRODUCT;

CREATE TABLE NEW_VEHICLE_TRIP_STATUS LIKE VEHICLE_TRIP_STATUS;
RENAME TABLE VEHICLE_TRIP_STATUS TO OLD_VEHICLE_TRIP_STATUS, NEW_VEHICLE_TRIP_STATUS to VEHICLE_TRIP_STATUS;
DROP TABLE OLD_VEHICLE_TRIP_STATUS;

CREATE TABLE NEW_VEHICLE_TRIP LIKE VEHICLE_TRIP;
RENAME TABLE VEHICLE_TRIP TO OLD_VEHICLE_TRIP, NEW_VEHICLE_TRIP to VEHICLE_TRIP;
DROP TABLE OLD_VEHICLE_TRIP;

SET foreign_key_checks = 1;

