--
--  This script will wipe out all transactional data (accounting, hr, sales/marketing) 
--  from the database.
--  
--
-- WARNING: Be absolutely sure you know what you're doing before running this script.
--
--

SET foreign_key_checks = 0;

--
-- Visits/Audit cleanup
--

CREATE TABLE NEW_SERVER_HIT LIKE SERVER_HIT;
RENAME TABLE SERVER_HIT TO OLD_SERVER_HIT, NEW_SERVER_HIT to SERVER_HIT;
DROP TABLE OLD_SERVER_HIT;

CREATE TABLE NEW_SERVER_HIT_BIN LIKE SERVER_HIT_BIN;
RENAME TABLE SERVER_HIT_BIN TO OLD_SERVER_HIT_BIN, NEW_SERVER_HIT_BIN to SERVER_HIT_BIN;
DROP TABLE OLD_SERVER_HIT_BIN;

CREATE TABLE NEW_USER_LOGIN_HISTORY LIKE USER_LOGIN_HISTORY;
RENAME TABLE USER_LOGIN_HISTORY TO OLD_USER_LOGIN_HISTORY, NEW_USER_LOGIN_HISTORY to USER_LOGIN_HISTORY;
DROP TABLE OLD_USER_LOGIN_HISTORY;

CREATE TABLE NEW_VISIT LIKE VISIT;
RENAME TABLE VISIT TO OLD_VISIT, NEW_VISIT to VISIT;
DROP TABLE OLD_VISIT;

CREATE TABLE NEW_VISITOR LIKE VISITOR;
RENAME TABLE VISITOR TO OLD_VISITOR, NEW_VISITOR to VISITOR;
DROP TABLE OLD_VISITOR;

CREATE TABLE NEW_ENTITY_AUDIT_LOG LIKE ENTITY_AUDIT_LOG;
RENAME TABLE ENTITY_AUDIT_LOG TO OLD_ENTITY_AUDIT_LOG, NEW_ENTITY_AUDIT_LOG to ENTITY_AUDIT_LOG;
DROP TABLE OLD_ENTITY_AUDIT_LOG;

CREATE TABLE NEW_ENTITY_SYNC_REMOVE LIKE ENTITY_SYNC_REMOVE;
RENAME TABLE ENTITY_SYNC_REMOVE TO OLD_ENTITY_SYNC_REMOVE, NEW_ENTITY_SYNC_REMOVE to ENTITY_SYNC_REMOVE;
DROP TABLE OLD_ENTITY_SYNC_REMOVE;  

--
--  Accounting transaction cleanup
--

UPDATE `FIN_ACCOUNT_TRANS` SET `GL_RECONCILIATION_ID`=NULL;
DELETE FROM `GL_RECONCILIATION_ENTRY`;

DELETE FROM `GL_RECONCILIATION`;

DELETE FROM `GL_ACCOUNT_HISTORY`;
UPDATE `GL_ACCOUNT` SET `POSTED_BALANCE`=0;
UPDATE `GL_ACCOUNT_ORGANIZATION` SET `POSTED_BALANCE`=0;

UPDATE `FIN_ACCOUNT` SET `ACTUAL_BALANCE`=0 ,`AVAILABLE_BALANCE`=0;

CREATE TABLE NEW_ENTITY_SYNC_REMOVE LIKE ENTITY_SYNC_REMOVE;
RENAME TABLE ENTITY_SYNC_REMOVE TO OLD_ENTITY_SYNC_REMOVE, NEW_ENTITY_SYNC_REMOVE to ENTITY_SYNC_REMOVE;
DROP TABLE OLD_ENTITY_SYNC_REMOVE;

SET foreign_key_checks = 0;
CREATE TABLE NEW_ACCTG_TRANS_ENTRY LIKE ACCTG_TRANS_ENTRY;
RENAME TABLE ACCTG_TRANS_ENTRY TO OLD_ACCTG_TRANS_ENTRY, NEW_ACCTG_TRANS_ENTRY to ACCTG_TRANS_ENTRY;
DROP TABLE OLD_ACCTG_TRANS_ENTRY;
SET foreign_key_checks = 1;

CREATE TABLE NEW_ACCTG_TRANS_ATTRIBUTE LIKE ACCTG_TRANS_ATTRIBUTE;
RENAME TABLE ACCTG_TRANS_ATTRIBUTE TO OLD_ACCTG_TRANS_ATTRIBUTE, NEW_ACCTG_TRANS_ATTRIBUTE to ACCTG_TRANS_ATTRIBUTE;
DROP TABLE OLD_ACCTG_TRANS_ATTRIBUTE;

CREATE TABLE NEW_ACCTG_TRANS LIKE ACCTG_TRANS;
RENAME TABLE ACCTG_TRANS TO OLD_ACCTG_TRANS, NEW_ACCTG_TRANS to ACCTG_TRANS;
DROP TABLE OLD_ACCTG_TRANS;

--
-- Rest of the transactions cleanup
--

CREATE TABLE NEW_API_HIT LIKE API_HIT;
RENAME TABLE API_HIT TO OLD_API_HIT, NEW_API_HIT to API_HIT;
DROP TABLE OLD_API_HIT;

CREATE TABLE NEW_BILL_OF_SALE_INVOICE_SEQUENCE LIKE BILL_OF_SALE_INVOICE_SEQUENCE;
RENAME TABLE BILL_OF_SALE_INVOICE_SEQUENCE TO OLD_BILL_OF_SALE_INVOICE_SEQUENCE, NEW_BILL_OF_SALE_INVOICE_SEQUENCE to BILL_OF_SALE_INVOICE_SEQUENCE;
DROP TABLE OLD_BILL_OF_SALE_INVOICE_SEQUENCE;

CREATE TABLE NEW_CRATE_CAN_ACCOUNT LIKE CRATE_CAN_ACCOUNT;
RENAME TABLE CRATE_CAN_ACCOUNT TO OLD_CRATE_CAN_ACCOUNT, NEW_CRATE_CAN_ACCOUNT to CRATE_CAN_ACCOUNT;
DROP TABLE OLD_CRATE_CAN_ACCOUNT;

CREATE TABLE NEW_DAILYINDENTDETAIL LIKE DAILYINDENTDETAIL;
RENAME TABLE DAILYINDENTDETAIL TO OLD_DAILYINDENTDETAIL, NEW_DAILYINDENTDETAIL to DAILYINDENTDETAIL;
DROP TABLE OLD_DAILYINDENTDETAIL;

CREATE TABLE NEW_DAILYINDENT LIKE DAILYINDENT;
RENAME TABLE DAILYINDENT TO OLD_DAILYINDENT, NEW_DAILYINDENT to DAILYINDENT;
DROP TABLE OLD_DAILYINDENT;

CREATE TABLE NEW_EMPL_DAILY_ATTENDANCE_DETAIL LIKE EMPL_DAILY_ATTENDANCE_DETAIL;
RENAME TABLE EMPL_DAILY_ATTENDANCE_DETAIL TO OLD_EMPL_DAILY_ATTENDANCE_DETAIL, NEW_EMPL_DAILY_ATTENDANCE_DETAIL to EMPL_DAILY_ATTENDANCE_DETAIL;
DROP TABLE OLD_EMPL_DAILY_ATTENDANCE_DETAIL;

CREATE TABLE NEW_EMPL_LEAVE_STATUS LIKE EMPL_LEAVE_STATUS;
RENAME TABLE EMPL_LEAVE_STATUS TO OLD_EMPL_LEAVE_STATUS, NEW_EMPL_LEAVE_STATUS to EMPL_LEAVE_STATUS;
DROP TABLE OLD_EMPL_LEAVE_STATUS;

CREATE TABLE NEW_EMPL_LEAVE LIKE EMPL_LEAVE;
RENAME TABLE EMPL_LEAVE TO OLD_EMPL_LEAVE, NEW_EMPL_LEAVE to EMPL_LEAVE;
DROP TABLE OLD_EMPL_LEAVE;

CREATE TABLE NEW_EMPL_LEAVE_BALANCE_STATUS LIKE EMPL_LEAVE_BALANCE_STATUS;
RENAME TABLE EMPL_LEAVE_BALANCE_STATUS TO OLD_EMPL_LEAVE_BALANCE_STATUS, NEW_EMPL_LEAVE_BALANCE_STATUS to EMPL_LEAVE_BALANCE_STATUS;
DROP TABLE OLD_EMPL_LEAVE_BALANCE_STATUS;

CREATE TABLE NEW_EMPL_PUNCH_RAW LIKE EMPL_PUNCH_RAW;
RENAME TABLE EMPL_PUNCH_RAW TO OLD_EMPL_PUNCH_RAW, NEW_EMPL_PUNCH_RAW to EMPL_PUNCH_RAW;
DROP TABLE OLD_EMPL_PUNCH_RAW;

CREATE TABLE NEW_EMPL_PUNCH LIKE EMPL_PUNCH;
RENAME TABLE EMPL_PUNCH TO OLD_EMPL_PUNCH, NEW_EMPL_PUNCH to EMPL_PUNCH;
DROP TABLE OLD_EMPL_PUNCH;

CREATE TABLE NEW_FACILITY_COMMISSION LIKE FACILITY_COMMISSION;
RENAME TABLE FACILITY_COMMISSION TO OLD_FACILITY_COMMISSION, NEW_FACILITY_COMMISSION to FACILITY_COMMISSION;
DROP TABLE OLD_FACILITY_COMMISSION;

CREATE TABLE NEW_FIN_ACCNT_TRANS_SEQUENCE LIKE FIN_ACCNT_TRANS_SEQUENCE;
RENAME TABLE FIN_ACCNT_TRANS_SEQUENCE TO OLD_FIN_ACCNT_TRANS_SEQUENCE, NEW_FIN_ACCNT_TRANS_SEQUENCE to FIN_ACCNT_TRANS_SEQUENCE;
DROP TABLE OLD_FIN_ACCNT_TRANS_SEQUENCE;

CREATE TABLE NEW_FIN_ACCOUNT_TRANS_ATTRIBUTE LIKE FIN_ACCOUNT_TRANS_ATTRIBUTE;
RENAME TABLE FIN_ACCOUNT_TRANS_ATTRIBUTE TO OLD_FIN_ACCOUNT_TRANS_ATTRIBUTE, NEW_FIN_ACCOUNT_TRANS_ATTRIBUTE to FIN_ACCOUNT_TRANS_ATTRIBUTE;
DROP TABLE OLD_FIN_ACCOUNT_TRANS_ATTRIBUTE;

CREATE TABLE NEW_FIN_ACCOUNT_TRANS LIKE FIN_ACCOUNT_TRANS;
RENAME TABLE FIN_ACCOUNT_TRANS TO OLD_FIN_ACCOUNT_TRANS, NEW_FIN_ACCOUNT_TRANS to FIN_ACCOUNT_TRANS;
DROP TABLE OLD_FIN_ACCOUNT_TRANS;

CREATE TABLE NEW_IMAGE_DATA_RESOURCE LIKE IMAGE_DATA_RESOURCE;
RENAME TABLE IMAGE_DATA_RESOURCE TO OLD_IMAGE_DATA_RESOURCE, NEW_IMAGE_DATA_RESOURCE to IMAGE_DATA_RESOURCE;
DROP TABLE OLD_IMAGE_DATA_RESOURCE;

CREATE TABLE NEW_INVOICE_STATUS LIKE INVOICE_STATUS;
RENAME TABLE INVOICE_STATUS TO OLD_INVOICE_STATUS, NEW_INVOICE_STATUS to INVOICE_STATUS;
DROP TABLE OLD_INVOICE_STATUS;

CREATE TABLE NEW_INVOICE_ROLE LIKE INVOICE_ROLE;
RENAME TABLE INVOICE_ROLE TO OLD_INVOICE_ROLE, NEW_INVOICE_ROLE to INVOICE_ROLE;
DROP TABLE OLD_INVOICE_ROLE;

CREATE TABLE NEW_INVOICE_ITEM LIKE INVOICE_ITEM;
RENAME TABLE INVOICE_ITEM TO OLD_INVOICE_ITEM, NEW_INVOICE_ITEM to INVOICE_ITEM;
DROP TABLE OLD_INVOICE_ITEM;

CREATE TABLE NEW_INVOICE_ATTRIBUTE LIKE INVOICE_ATTRIBUTE;
RENAME TABLE INVOICE_ATTRIBUTE TO OLD_INVOICE_ATTRIBUTE, NEW_INVOICE_ATTRIBUTE to INVOICE_ATTRIBUTE;
DROP TABLE OLD_INVOICE_ATTRIBUTE;

CREATE TABLE NEW_INVOICE_CONTACT_MECH LIKE INVOICE_CONTACT_MECH;
RENAME TABLE INVOICE_CONTACT_MECH TO OLD_INVOICE_CONTACT_MECH, NEW_INVOICE_CONTACT_MECH to INVOICE_CONTACT_MECH;
DROP TABLE OLD_INVOICE_CONTACT_MECH;

CREATE TABLE NEW_INVOICE LIKE INVOICE;
RENAME TABLE INVOICE TO OLD_INVOICE, NEW_INVOICE to INVOICE;
DROP TABLE OLD_INVOICE;

CREATE TABLE NEW_ITEM_ISSUANCE LIKE ITEM_ISSUANCE;
RENAME TABLE ITEM_ISSUANCE TO OLD_ITEM_ISSUANCE, NEW_ITEM_ISSUANCE to ITEM_ISSUANCE;
DROP TABLE OLD_ITEM_ISSUANCE;

CREATE TABLE NEW_JOB_SANDBOX LIKE JOB_SANDBOX;
RENAME TABLE JOB_SANDBOX TO OLD_JOB_SANDBOX, NEW_JOB_SANDBOX to JOB_SANDBOX;
DROP TABLE OLD_JOB_SANDBOX;

CREATE TABLE NEW_LOAN_RECOVERY LIKE LOAN_RECOVERY;
RENAME TABLE LOAN_RECOVERY TO OLD_LOAN_RECOVERY, NEW_LOAN_RECOVERY to LOAN_RECOVERY;
DROP TABLE OLD_LOAN_RECOVERY;

CREATE TABLE NEW_ORDER_ADJUSTMENT_BILLING LIKE ORDER_ADJUSTMENT_BILLING;
RENAME TABLE ORDER_ADJUSTMENT_BILLING TO OLD_ORDER_ADJUSTMENT_BILLING, NEW_ORDER_ADJUSTMENT_BILLING to ORDER_ADJUSTMENT_BILLING;
DROP TABLE OLD_ORDER_ADJUSTMENT_BILLING;

CREATE TABLE NEW_ORDER_ADJUSTMENT LIKE ORDER_ADJUSTMENT;
RENAME TABLE ORDER_ADJUSTMENT TO OLD_ORDER_ADJUSTMENT, NEW_ORDER_ADJUSTMENT to ORDER_ADJUSTMENT;
DROP TABLE OLD_ORDER_ADJUSTMENT;

CREATE TABLE NEW_ORDER_ATTRIBUTE LIKE ORDER_ATTRIBUTE;
RENAME TABLE ORDER_ATTRIBUTE TO OLD_ORDER_ATTRIBUTE, NEW_ORDER_ATTRIBUTE to ORDER_ATTRIBUTE;
DROP TABLE OLD_ORDER_ATTRIBUTE;

CREATE TABLE NEW_ORDER_ITEM_BILLING LIKE ORDER_ITEM_BILLING;
RENAME TABLE ORDER_ITEM_BILLING TO OLD_ORDER_ITEM_BILLING, NEW_ORDER_ITEM_BILLING to ORDER_ITEM_BILLING;
DROP TABLE OLD_ORDER_ITEM_BILLING;

CREATE TABLE NEW_ORDER_ITEM_SHIP_GROUP_ASSOC LIKE ORDER_ITEM_SHIP_GROUP_ASSOC;
RENAME TABLE ORDER_ITEM_SHIP_GROUP_ASSOC TO OLD_ORDER_ITEM_SHIP_GROUP_ASSOC, NEW_ORDER_ITEM_SHIP_GROUP_ASSOC to ORDER_ITEM_SHIP_GROUP_ASSOC;
DROP TABLE OLD_ORDER_ITEM_SHIP_GROUP_ASSOC;

CREATE TABLE NEW_ORDER_ITEM_SHIP_GROUP LIKE ORDER_ITEM_SHIP_GROUP;
RENAME TABLE ORDER_ITEM_SHIP_GROUP TO OLD_ORDER_ITEM_SHIP_GROUP, NEW_ORDER_ITEM_SHIP_GROUP to ORDER_ITEM_SHIP_GROUP;
DROP TABLE OLD_ORDER_ITEM_SHIP_GROUP;

CREATE TABLE NEW_ORDER_ITEM LIKE ORDER_ITEM;
RENAME TABLE ORDER_ITEM TO OLD_ORDER_ITEM, NEW_ORDER_ITEM to ORDER_ITEM;
DROP TABLE OLD_ORDER_ITEM;

CREATE TABLE NEW_ORDER_ROLE LIKE ORDER_ROLE;
RENAME TABLE ORDER_ROLE TO OLD_ORDER_ROLE, NEW_ORDER_ROLE to ORDER_ROLE;
DROP TABLE OLD_ORDER_ROLE;

CREATE TABLE NEW_ORDER_HEADER LIKE ORDER_HEADER;
RENAME TABLE ORDER_HEADER TO OLD_ORDER_HEADER, NEW_ORDER_HEADER to ORDER_HEADER;
DROP TABLE OLD_ORDER_HEADER;

CREATE TABLE NEW_PAYMENT_APPLICATION LIKE PAYMENT_APPLICATION;
RENAME TABLE PAYMENT_APPLICATION TO OLD_PAYMENT_APPLICATION, NEW_PAYMENT_APPLICATION to PAYMENT_APPLICATION;
DROP TABLE OLD_PAYMENT_APPLICATION;

CREATE TABLE NEW_PAYMENT_ATTRIBUTE LIKE PAYMENT_ATTRIBUTE;
RENAME TABLE PAYMENT_ATTRIBUTE TO OLD_PAYMENT_ATTRIBUTE, NEW_PAYMENT_ATTRIBUTE to PAYMENT_ATTRIBUTE;
DROP TABLE OLD_PAYMENT_ATTRIBUTE;

CREATE TABLE NEW_PAYMENT_GROUP_MEMBER LIKE PAYMENT_GROUP_MEMBER;
RENAME TABLE PAYMENT_GROUP_MEMBER TO OLD_PAYMENT_GROUP_MEMBER, NEW_PAYMENT_GROUP_MEMBER to PAYMENT_GROUP_MEMBER;
DROP TABLE OLD_PAYMENT_GROUP_MEMBER;

CREATE TABLE NEW_PAYMENT_GROUP LIKE PAYMENT_GROUP;
RENAME TABLE PAYMENT_GROUP TO OLD_PAYMENT_GROUP, NEW_PAYMENT_GROUP to PAYMENT_GROUP;
DROP TABLE OLD_PAYMENT_GROUP;

CREATE TABLE NEW_PAYMENT LIKE PAYMENT;
RENAME TABLE PAYMENT TO OLD_PAYMENT, NEW_PAYMENT to PAYMENT;
DROP TABLE OLD_PAYMENT;

CREATE TABLE NEW_PAYROLL_ATTENDANCE_SHIFT_WISE LIKE PAYROLL_ATTENDANCE_SHIFT_WISE;
RENAME TABLE PAYROLL_ATTENDANCE_SHIFT_WISE TO OLD_PAYROLL_ATTENDANCE_SHIFT_WISE, NEW_PAYROLL_ATTENDANCE_SHIFT_WISE to PAYROLL_ATTENDANCE_SHIFT_WISE;
DROP TABLE OLD_PAYROLL_ATTENDANCE_SHIFT_WISE;

CREATE TABLE NEW_PAYROLL_ATTENDANCE LIKE PAYROLL_ATTENDANCE;
RENAME TABLE PAYROLL_ATTENDANCE TO OLD_PAYROLL_ATTENDANCE, NEW_PAYROLL_ATTENDANCE to PAYROLL_ATTENDANCE;
DROP TABLE OLD_PAYROLL_ATTENDANCE;

CREATE TABLE NEW_PAYROLL_HEADER_ITEM LIKE PAYROLL_HEADER_ITEM;
RENAME TABLE PAYROLL_HEADER_ITEM TO OLD_PAYROLL_HEADER_ITEM, NEW_PAYROLL_HEADER_ITEM to PAYROLL_HEADER_ITEM;
DROP TABLE OLD_PAYROLL_HEADER_ITEM;

CREATE TABLE NEW_PAYROLL_HEADER LIKE PAYROLL_HEADER;
RENAME TABLE PAYROLL_HEADER TO OLD_PAYROLL_HEADER, NEW_PAYROLL_HEADER to PAYROLL_HEADER;
DROP TABLE OLD_PAYROLL_HEADER;

CREATE TABLE NEW_RETURN_STATUS LIKE RETURN_STATUS;
RENAME TABLE RETURN_STATUS TO OLD_RETURN_STATUS, NEW_RETURN_STATUS to RETURN_STATUS;
DROP TABLE OLD_RETURN_STATUS;

CREATE TABLE NEW_RETURN_REASON LIKE RETURN_REASON;
RENAME TABLE RETURN_REASON TO OLD_RETURN_REASON, NEW_RETURN_REASON to RETURN_REASON;
DROP TABLE OLD_RETURN_REASON;

CREATE TABLE NEW_RETURN_ITEM LIKE RETURN_ITEM;
RENAME TABLE RETURN_ITEM TO OLD_RETURN_ITEM, NEW_RETURN_ITEM to RETURN_ITEM;
DROP TABLE OLD_RETURN_ITEM;

CREATE TABLE NEW_RETURN_HEADER LIKE RETURN_HEADER;
RENAME TABLE RETURN_HEADER TO OLD_RETURN_HEADER, NEW_RETURN_HEADER to RETURN_HEADER;
DROP TABLE OLD_RETURN_HEADER;

CREATE TABLE NEW_RUNTIME_DATA LIKE RUNTIME_DATA;
RENAME TABLE RUNTIME_DATA TO OLD_RUNTIME_DATA, NEW_RUNTIME_DATA to RUNTIME_DATA;
DROP TABLE OLD_RUNTIME_DATA;

CREATE TABLE NEW_SHIPMENT LIKE SHIPMENT;
RENAME TABLE SHIPMENT TO OLD_SHIPMENT, NEW_SHIPMENT to SHIPMENT;
DROP TABLE OLD_SHIPMENT;

CREATE TABLE NEW_SUBSCRIPTION_PRODUCT LIKE SUBSCRIPTION_PRODUCT;
RENAME TABLE SUBSCRIPTION_PRODUCT TO OLD_SUBSCRIPTION_PRODUCT, NEW_SUBSCRIPTION_PRODUCT to SUBSCRIPTION_PRODUCT;
DROP TABLE OLD_SUBSCRIPTION_PRODUCT;

CREATE TABLE NEW_VEHICLE_TRIP_STATUS LIKE VEHICLE_TRIP_STATUS;
RENAME TABLE VEHICLE_TRIP_STATUS TO OLD_VEHICLE_TRIP_STATUS, NEW_VEHICLE_TRIP_STATUS to VEHICLE_TRIP_STATUS;
DROP TABLE OLD_VEHICLE_TRIP_STATUS;

CREATE TABLE NEW_VEHICLE_TRIP LIKE VEHICLE_TRIP;
RENAME TABLE VEHICLE_TRIP TO OLD_VEHICLE_TRIP, NEW_VEHICLE_TRIP to VEHICLE_TRIP;
DROP TABLE OLD_VEHICLE_TRIP;

CREATE TABLE NEW_PRODUCT_SEARCH_RESULT LIKE PRODUCT_SEARCH_RESULT;
RENAME TABLE PRODUCT_SEARCH_RESULT TO OLD_PRODUCT_SEARCH_RESULT, NEW_PRODUCT_SEARCH_RESULT to PRODUCT_SEARCH_RESULT;
DROP TABLE OLD_PRODUCT_SEARCH_RESULT;

CREATE TABLE NEW_PRODUCT_SEARCH_CONSTRAINT LIKE PRODUCT_SEARCH_CONSTRAINT;
RENAME TABLE PRODUCT_SEARCH_CONSTRAINT TO OLD_PRODUCT_SEARCH_CONSTRAINT, NEW_PRODUCT_SEARCH_CONSTRAINT to PRODUCT_SEARCH_CONSTRAINT;
DROP TABLE OLD_PRODUCT_SEARCH_CONSTRAINT;

SET foreign_key_checks = 1;


ALTER TABLE `ORDER_ITEM_PRICE_INFO` DROP FOREIGN KEY `ORDER_OIPI_OITM`;
ALTER TABLE `ORDER_ITEM_PRICE_INFO` DROP INDEX `ORDER_OIPI_OITM`;
ALTER TABLE `ORDER_ITEM_PRICE_INFO` ADD CONSTRAINT `ORDER_OIPI_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_STATUS` DROP FOREIGN KEY `ORDER_STTS_OHDR`;
ALTER TABLE `ORDER_STATUS` DROP INDEX `ORDER_STTS_OHDR`;
ALTER TABLE `ORDER_STATUS` ADD CONSTRAINT `ORDER_STTS_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_ITEM_ROLE` DROP FOREIGN KEY `ORDER_ITRL_OITM`;
ALTER TABLE `ORDER_ITEM_ROLE` DROP INDEX `ORDER_ITRL_OITM`;
ALTER TABLE `ORDER_ITEM_ROLE` ADD CONSTRAINT `ORDER_ITRL_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_ROLE` DROP FOREIGN KEY `ORDER_ITRL_OHDR`;
ALTER TABLE `ORDER_ITEM_ROLE` DROP INDEX `ORDER_ITRL_OHDR`;
ALTER TABLE `ORDER_ITEM_ROLE` ADD CONSTRAINT `ORDER_ITRL_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_TERM` DROP FOREIGN KEY `ORDER_TERM_OHDR`;
ALTER TABLE `ORDER_TERM` DROP INDEX `ORDER_TERM_OHDR`;
ALTER TABLE `ORDER_TERM` ADD CONSTRAINT `ORDER_TERM_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_SHIPMENT_PREFERENCE` DROP FOREIGN KEY `ORDER_SHPREF_OHDR`;
ALTER TABLE `ORDER_SHIPMENT_PREFERENCE` DROP INDEX `ORDER_SHPREF_OHDR`;
ALTER TABLE `ORDER_SHIPMENT_PREFERENCE` ADD CONSTRAINT `ORDER_SHPREF_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_SHIPMENT` DROP FOREIGN KEY `ORDER_SHPMT_OHDR`;
ALTER TABLE `ORDER_SHIPMENT` DROP INDEX `ORDER_SHPMT_OHDR`;
ALTER TABLE `ORDER_SHIPMENT` ADD CONSTRAINT `ORDER_SHPMT_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_SHIPMENT` DROP FOREIGN KEY `ORDER_SHPMT_SHPMT`;
ALTER TABLE `ORDER_SHIPMENT` DROP INDEX `ORDER_SHPMT_SHPMT`;
ALTER TABLE `ORDER_SHIPMENT` ADD CONSTRAINT `ORDER_SHPMT_SHPMT` FOREIGN KEY (`SHIPMENT_ID`) REFERENCES `SHIPMENT` (`SHIPMENT_ID`);

ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` DROP FOREIGN KEY `ORDREQ_CMT_ORD`;
ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` DROP INDEX `ORDREQ_CMT_ORD`;
ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` ADD CONSTRAINT `ORDREQ_CMT_ORD` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` DROP FOREIGN KEY `ORDREQ_CMT_OITM`;
ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` DROP INDEX `ORDREQ_CMT_OITM`;
ALTER TABLE `ORDER_REQUIREMENT_COMMITMENT` ADD CONSTRAINT `ORDREQ_CMT_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_PRODUCT_PROMO_CODE` DROP FOREIGN KEY `ORDER_PPCD_ORD`;
ALTER TABLE `ORDER_PRODUCT_PROMO_CODE` DROP INDEX `ORDER_PPCD_ORD`;
ALTER TABLE `ORDER_PRODUCT_PROMO_CODE` ADD CONSTRAINT `ORDER_PPCD_ORD` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);


ALTER TABLE `ORDER_PAYMENT_PREFERENCE` DROP FOREIGN KEY `ORDER_PMPRF_OHDR`;
ALTER TABLE `ORDER_PAYMENT_PREFERENCE` DROP INDEX `ORDER_PMPRF_OHDR`;
ALTER TABLE `ORDER_PAYMENT_PREFERENCE` ADD CONSTRAINT `ORDER_PMPRF_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_NOTIFICATION` DROP FOREIGN KEY `ORD_NOTIFY_ORDHDR`;
ALTER TABLE `ORDER_NOTIFICATION` DROP INDEX `ORD_NOTIFY_ORDHDR`;
ALTER TABLE `ORDER_NOTIFICATION` ADD CONSTRAINT `ORD_NOTIFY_ORDHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);

ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` DROP FOREIGN KEY `ORDER_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` DROP INDEX `ORDER_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` ADD CONSTRAINT `ORDER_ITIR_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);



ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` DROP FOREIGN KEY `ORDER_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` DROP INDEX `ORDER_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_SHIP_GRP_INV_RES` ADD CONSTRAINT `ORDER_ITIR_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
CREATE INDEX `ORDER_ITIR_OITM` ON `ORDER_ITEM_SHIP_GRP_INV_RES`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_INVENTORY_RES` DROP FOREIGN KEY `OLDODR_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_INVENTORY_RES` DROP INDEX `OLDODR_ITIR_OITM`;
ALTER TABLE `ORDER_ITEM_INVENTORY_RES` ADD CONSTRAINT `OLDODR_ITIR_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
CREATE INDEX `OLDODR_ITIR_OITM` ON `ORDER_ITEM_INVENTORY_RES`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_GROUP` DROP FOREIGN KEY `ORDERITMGRP_HDR`;
ALTER TABLE `ORDER_ITEM_GROUP` DROP INDEX `ORDERITMGRP_HDR`;
ALTER TABLE `ORDER_ITEM_GROUP` ADD CONSTRAINT `ORDERITMGRP_HDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDERITMGRP_HDR` ON `ORDER_ITEM_GROUP`(`ORDER_ID`);

ALTER TABLE `ORDER_ITEM_CONTACT_MECH` DROP FOREIGN KEY `ORDER_ITCM_OITM`;
ALTER TABLE `ORDER_ITEM_CONTACT_MECH` DROP INDEX `ORDER_ITCM_OITM`;
ALTER TABLE `ORDER_ITEM_CONTACT_MECH` ADD CONSTRAINT `ORDER_ITCM_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
CREATE INDEX `ORDER_ITCM_OITM` ON `ORDER_ITEM_CONTACT_MECH`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_CHANGE` DROP FOREIGN KEY `ORDER_ITCH_OITM`;
ALTER TABLE `ORDER_ITEM_CHANGE` DROP INDEX `ORDER_ITCH_OITM`;
ALTER TABLE `ORDER_ITEM_CHANGE` ADD CONSTRAINT `ORDER_ITCH_OITM` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `ORDER_ITCH_OITM` ON `ORDER_ITEM_CHANGE`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_ATTRIBUTE` DROP FOREIGN KEY `ORDER_ITEM_ATTR`;
ALTER TABLE `ORDER_ITEM_ATTRIBUTE` DROP INDEX `ORDER_ITEM_ATTR`;
ALTER TABLE `ORDER_ITEM_ATTRIBUTE` ADD CONSTRAINT `ORDER_ITEM_ATTR` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
CREATE INDEX `ORDER_ITEM_ATTR` ON `ORDER_ITEM_ATTRIBUTE`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP FOREIGN KEY `ORDER_ITASSC_SOHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP INDEX `ORDER_ITASSC_SOHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` ADD CONSTRAINT `ORDER_ITASSC_SOHD` FOREIGN KEY (`SALES_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_ITASSC_SOHD` ON `ORDER_ITEM_ASSOCIATION`(`SALES_ORDER_ID`);

ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP FOREIGN KEY `ORDER_ITASSC_SOHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP INDEX `ORDER_ITASSC_SOHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` ADD CONSTRAINT `ORDER_ITASSC_SOHD` FOREIGN KEY (`SALES_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_ITASSC_SOHD` ON `ORDER_ITEM_ASSOCIATION`(`SALES_ORDER_ID`);

ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP FOREIGN KEY `ORDER_ITASSC_POHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` DROP INDEX `ORDER_ITASSC_POHD`;
ALTER TABLE `ORDER_ITEM_ASSOCIATION` ADD CONSTRAINT `ORDER_ITASSC_POHD` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
-- CREATE INDEX `ORDER_ITASSC_POHD` ON `ORDER_ITEM_ASSOCIATION`(`PURCHASE_ORDER_ID`);

ALTER TABLE `ORDER_ITEM_ASSOC` DROP FOREIGN KEY `ORDER_ITASS_TOHD`;
ALTER TABLE `ORDER_ITEM_ASSOC` DROP INDEX `ORDER_ITASS_TOHD`;
ALTER TABLE `ORDER_ITEM_ASSOC` ADD CONSTRAINT `ORDER_ITASS_TOHD` FOREIGN KEY (`TO_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
--CREATE INDEX `ORDER_ITASS_TOHD` ON `ORDER_ITEM_ASSOC`(`TO_ORDER_ID`);

ALTER TABLE `ORDER_ITEM_ASSOC` DROP FOREIGN KEY `ORDER_ITASS_FRHD`;
ALTER TABLE `ORDER_ITEM_ASSOC` DROP INDEX `ORDER_ITASS_FRHD`;
ALTER TABLE `ORDER_ITEM_ASSOC` ADD CONSTRAINT `ORDER_ITASS_FRHD` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_ITASS_FRHD` ON `ORDER_ITEM_ASSOC`(`ORDER_ID`);

ALTER TABLE `ORDER_HEADER_WORK_EFFORT` DROP FOREIGN KEY `ORDERHDWE_OH`;
ALTER TABLE `ORDER_HEADER_WORK_EFFORT` DROP INDEX `ORDERHDWE_OH`;
ALTER TABLE `ORDER_HEADER_WORK_EFFORT` ADD CONSTRAINT `ORDERHDWE_OH` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDERHDWE_OH` ON `ORDER_HEADER_WORK_EFFORT`(`ORDER_ID`);

ALTER TABLE `ORDER_HEADER_NOTE` DROP FOREIGN KEY `ORDER_HDRNT_HDR`;
ALTER TABLE `ORDER_HEADER_NOTE` DROP INDEX `ORDER_HDRNT_HDR`;
ALTER TABLE `ORDER_HEADER_NOTE` ADD CONSTRAINT `ORDER_HDRNT_HDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_HDRNT_HDR` ON `ORDER_HEADER_NOTE`(`ORDER_ID`);

ALTER TABLE `ORDER_DELIVERY_SCHEDULE` DROP FOREIGN KEY `ORDER_DELSCH_OHDR`;
ALTER TABLE `ORDER_DELIVERY_SCHEDULE` DROP INDEX `ORDER_DELSCH_OHDR`;
ALTER TABLE `ORDER_DELIVERY_SCHEDULE` ADD CONSTRAINT `ORDER_DELSCH_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_DELSCH_OHDR` ON `ORDER_DELIVERY_SCHEDULE`(`ORDER_ID`);

ALTER TABLE `ORDER_CONTENT` DROP FOREIGN KEY `ORD_CNT_PROD`;
ALTER TABLE `ORDER_CONTENT` DROP INDEX `ORD_CNT_PROD`;
ALTER TABLE `ORDER_CONTENT` ADD CONSTRAINT `ORD_CNT_PROD` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
--CREATE INDEX `ORD_CNT_PROD` ON `ORDER_CONTENT`(`ORDER_ID`);

ALTER TABLE `ORDER_CONTACT_MECH` DROP FOREIGN KEY `ORDER_CMECH_HDR`;
ALTER TABLE `ORDER_CONTACT_MECH` DROP INDEX `ORDER_CMECH_HDR`;
ALTER TABLE `ORDER_CONTACT_MECH` ADD CONSTRAINT `ORDER_CMECH_HDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `ORDER_CMECH_HDR` ON `ORDER_CONTACT_MECH`(`ORDER_ID`);

ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` DROP FOREIGN KEY `ORDER_ADJ_ATTR`;
ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` DROP INDEX `ORDER_ADJ_ATTR`;
ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` ADD CONSTRAINT `ORDER_ADJ_ATTR` FOREIGN KEY (`ORDER_ADJUSTMENT_ID`) REFERENCES `ORDER_ADJUSTMENT` (`ORDER_ADJUSTMENT_ID`);
CREATE INDEX `ORDER_ADJ_ATTR` ON `ORDER_ADJUSTMENT_ATTRIBUTE`(`ORDER_ADJUSTMENT_ID`);

ALTER TABLE `MILK_CARD_ORDER` DROP FOREIGN KEY `MCARD_INV`;
ALTER TABLE `MILK_CARD_ORDER` DROP INDEX `MCARD_INV`;
ALTER TABLE `MILK_CARD_ORDER` ADD CONSTRAINT `MCARD_INV` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE` (`INVOICE_ID`);
--CREATE INDEX `MCARD_INV` ON `MILK_CARD_ORDER`(`INVOICE_ID`);

ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` DROP FOREIGN KEY `ORDER_ADJ_ATTR`;
ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` DROP INDEX `ORDER_ADJ_ATTR`;
ALTER TABLE `ORDER_ADJUSTMENT_ATTRIBUTE` ADD CONSTRAINT `ORDER_ADJ_ATTR` FOREIGN KEY (`ORDER_ADJUSTMENT_ID`) REFERENCES `ORDER_ADJUSTMENT` (`ORDER_ADJUSTMENT_ID`);
CREATE INDEX `ORDER_ADJ_ATTR` ON `ORDER_ADJUSTMENT_ATTRIBUTE`(`ORDER_ADJUSTMENT_ID`);

ALTER TABLE `ITEM_ISSUANCE_ROLE` DROP FOREIGN KEY `ITEM_ISSRL_ITMIS`;
ALTER TABLE `ITEM_ISSUANCE_ROLE` DROP INDEX `ITEM_ISSRL_ITMIS`;
ALTER TABLE `ITEM_ISSUANCE_ROLE` ADD CONSTRAINT `ITEM_ISSRL_ITMIS` FOREIGN KEY (`ITEM_ISSUANCE_ID`) REFERENCES `ITEM_ISSUANCE` (`ITEM_ISSUANCE_ID`);
CREATE INDEX `ITEM_ISSRL_ITMIS` ON `ITEM_ISSUANCE_ROLE`(`ITEM_ISSUANCE_ID`);

ALTER TABLE `INVOICE_TERM` DROP FOREIGN KEY `INVCE_TRM_INVCE`;
ALTER TABLE `INVOICE_TERM` DROP INDEX `INVCE_TRM_INVCE`;
ALTER TABLE `INVOICE_TERM` ADD CONSTRAINT `INVCE_TRM_INVCE` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE` (`INVOICE_ID`);
--CREATE INDEX `INVCE_TRM_INVCE` ON `INVOICE_TERM`(`INVOICE_ID`);

ALTER TABLE `INVOICE_ROLE` DROP FOREIGN KEY `INVCE_RLE_INVCE`;
ALTER TABLE `INVOICE_ROLE` DROP INDEX `INVCE_RLE_INVCE`;
ALTER TABLE `INVOICE_ROLE` ADD CONSTRAINT `INVCE_RLE_INVCE` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE` (`INVOICE_ID`);
CREATE INDEX `INVCE_RLE_INVCE` ON `INVOICE_ROLE`(`INVOICE_ID`);

ALTER TABLE `INVOICE_ITEM_ATTRIBUTE` DROP FOREIGN KEY `INVOICE_IMAT_ITM`;
ALTER TABLE `INVOICE_ITEM_ATTRIBUTE` DROP INDEX `INVOICE_IMAT_ITM`;
ALTER TABLE `INVOICE_ITEM_ATTRIBUTE` ADD CONSTRAINT `INVOICE_IMAT_ITM` FOREIGN KEY (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`) REFERENCES `INVOICE_ITEM` (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);
CREATE INDEX `INVOICE_IMAT_ITM` ON `INVOICE_ITEM_ATTRIBUTE`(`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);

ALTER TABLE `INVOICE_ITEM_ASSOC` DROP FOREIGN KEY `INITMASC_TIITM`;
ALTER TABLE `INVOICE_ITEM_ASSOC` DROP INDEX `INITMASC_TIITM`;
ALTER TABLE `INVOICE_ITEM_ASSOC` ADD CONSTRAINT `INITMASC_TIITM` FOREIGN KEY (`INVOICE_ID_TO`, `INVOICE_ITEM_SEQ_ID_TO`) REFERENCES `INVOICE_ITEM` (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);
--CREATE INDEX `INITMASC_TIITM` ON `INVOICE_ITEM_ASSOC`(`INVOICE_ID_TO`, `INVOICE_ITEM_SEQ_ID_TO`);

ALTER TABLE `INVOICE_ITEM_ASSOC` DROP FOREIGN KEY `INITMASC_FIITM`;
ALTER TABLE `INVOICE_ITEM_ASSOC` DROP INDEX `INITMASC_FIITM`;
ALTER TABLE `INVOICE_ITEM_ASSOC` ADD CONSTRAINT `INITMASC_FIITM` FOREIGN KEY (`INVOICE_ID_FROM`, `INVOICE_ITEM_SEQ_ID_FROM`) REFERENCES `INVOICE_ITEM` (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);
CREATE INDEX `INITMASC_FIITM` ON `INVOICE_ITEM_ASSOC`(`INVOICE_ID_FROM`, `INVOICE_ITEM_SEQ_ID_FROM`);

ALTER TABLE `INVENTORY_TRANSFER` DROP FOREIGN KEY `INV_XFER_ISSU`;
ALTER TABLE `INVENTORY_TRANSFER` DROP INDEX `INV_XFER_ISSU`;
ALTER TABLE `INVENTORY_TRANSFER` ADD CONSTRAINT `INV_XFER_ISSU` FOREIGN KEY (`ITEM_ISSUANCE_ID`) REFERENCES `ITEM_ISSUANCE` (`ITEM_ISSUANCE_ID`);
--CREATE INDEX `INV_XFER_ISSU` ON `INVENTORY_TRANSFER`(`ITEM_ISSUANCE_ID`);

ALTER TABLE `INVENTORY_ITEM_DETAIL` DROP FOREIGN KEY `INV_ITDTL_ITMIS`;
ALTER TABLE `INVENTORY_ITEM_DETAIL` DROP INDEX `INV_ITDTL_ITMIS`;
ALTER TABLE `INVENTORY_ITEM_DETAIL` ADD CONSTRAINT `INV_ITDTL_ITMIS` FOREIGN KEY (`ITEM_ISSUANCE_ID`) REFERENCES `ITEM_ISSUANCE` (`ITEM_ISSUANCE_ID`);
--CREATE INDEX `INV_ITDTL_ITMIS` ON `INVENTORY_ITEM_DETAIL`(`ITEM_ISSUANCE_ID`);


ALTER TABLE `COMMUNICATION_EVENT_ORDER` DROP FOREIGN KEY `COMEV_ORDER_ORDER`;
ALTER TABLE `COMMUNICATION_EVENT_ORDER` DROP INDEX `COMEV_ORDER_ORDER`;
ALTER TABLE `COMMUNICATION_EVENT_ORDER` ADD CONSTRAINT `COMEV_ORDER_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `COMEV_ORDER_ORDER` ON `COMMUNICATION_EVENT_ORDER`(`ORDER_ID`);

ALTER TABLE `FIXED_ASSET_MAINT` DROP FOREIGN KEY `FXDASTMNT_PURORD`;
ALTER TABLE `FIXED_ASSET_MAINT` DROP INDEX `FXDASTMNT_PURORD`;
ALTER TABLE `FIXED_ASSET_MAINT` ADD CONSTRAINT `FXDASTMNT_PURORD` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
--CREATE INDEX `FXDASTMNT_PURORD` ON `FIXED_ASSET_MAINT`(`PURCHASE_ORDER_ID`);

ALTER TABLE `FIXED_ASSET_MAINT_ORDER` DROP FOREIGN KEY `FXDASTMNT_ORD`;
ALTER TABLE `FIXED_ASSET_MAINT_ORDER` DROP INDEX `FXDASTMNT_ORD`;
ALTER TABLE `FIXED_ASSET_MAINT_ORDER` ADD CONSTRAINT `FXDASTMNT_ORD` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
--CREATE INDEX `FXDASTMNT_ORD` ON `FIXED_ASSET_MAINT_ORDER`(`ORDER_ID`);

ALTER TABLE `GIFT_CARD_FULFILLMENT` DROP FOREIGN KEY `GC_FILL_ODRH`;
ALTER TABLE `GIFT_CARD_FULFILLMENT` DROP INDEX `GC_FILL_ODRH`;
ALTER TABLE `GIFT_CARD_FULFILLMENT` ADD CONSTRAINT `GC_FILL_ODRH` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `GC_FILL_ODRH` ON `GIFT_CARD_FULFILLMENT`(`ORDER_ID`);

ALTER TABLE `PRODUCT_ORDER_ITEM` DROP FOREIGN KEY `PROD_OITEM_ENOHDR`;
ALTER TABLE `PRODUCT_ORDER_ITEM` DROP INDEX `PROD_OITEM_ENOHDR`;
ALTER TABLE `PRODUCT_ORDER_ITEM` ADD CONSTRAINT `PROD_OITEM_ENOHDR` FOREIGN KEY (`ENGAGEMENT_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `PROD_OITEM_ENOHDR` ON `PRODUCT_ORDER_ITEM`(`ENGAGEMENT_ID`);

ALTER TABLE `PRODUCT_ORDER_ITEM` DROP FOREIGN KEY `PROD_OITEM_OHDR`;
ALTER TABLE `PRODUCT_ORDER_ITEM` DROP INDEX `PROD_OITEM_OHDR`;
ALTER TABLE `PRODUCT_ORDER_ITEM` ADD CONSTRAINT `PROD_OITEM_OHDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `PROD_OITEM_OHDR` ON `PRODUCT_ORDER_ITEM`(`ORDER_ID`);

ALTER TABLE `PRODUCT_PROMO_USE` DROP FOREIGN KEY `PROD_PRUSE_ORDR`;
ALTER TABLE `PRODUCT_PROMO_USE` DROP INDEX `PROD_PRUSE_ORDR`;
ALTER TABLE `PRODUCT_PROMO_USE` ADD CONSTRAINT `PROD_PRUSE_ORDR` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
CREATE INDEX `PROD_PRUSE_ORDR` ON `PRODUCT_PROMO_USE`(`ORDER_ID`);

ALTER TABLE `RETURN_ITEM_RESPONSE` DROP FOREIGN KEY `RTN_RESP_NEWORD`;
ALTER TABLE `RETURN_ITEM_RESPONSE` DROP INDEX `RTN_RESP_NEWORD`;
ALTER TABLE `RETURN_ITEM_RESPONSE` ADD CONSTRAINT `RTN_RESP_NEWORD` FOREIGN KEY (`REPLACEMENT_ORDER_ID`) REFERENCES `ORDER_HEADER` (`ORDER_ID`);
--CREATE INDEX `RTN_RESP_NEWORD` ON `RETURN_ITEM_RESPONSE`(`REPLACEMENT_ORDER_ID`);

ALTER TABLE `FIXED_ASSET` DROP FOREIGN KEY `FIXEDAST_ORDITM`;
ALTER TABLE `FIXED_ASSET` DROP INDEX `FIXEDAST_ORDITM`;
ALTER TABLE `FIXED_ASSET` ADD CONSTRAINT `FIXEDAST_ORDITM` FOREIGN KEY (`ACQUIRE_ORDER_ID`, `ACQUIRE_ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `FIXEDAST_ORDITM` ON `FIXED_ASSET`(`ACQUIRE_ORDER_ID`, `ACQUIRE_ORDER_ITEM_SEQ_ID`);

ALTER TABLE `PICKLIST_ITEM` DROP FOREIGN KEY `PCKLST_ITM_ODIT`;
ALTER TABLE `PICKLIST_ITEM` DROP INDEX `PCKLST_ITM_ODIT`;
ALTER TABLE `PICKLIST_ITEM` ADD CONSTRAINT `PCKLST_ITM_ODIT` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `PCKLST_ITM_ODIT` ON `PICKLIST_ITEM`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `PROC_BILLING_VALIDATION` DROP FOREIGN KEY `PROC_BILV_OIT`;
ALTER TABLE `PROC_BILLING_VALIDATION` DROP INDEX `PROC_BILV_OIT`;
ALTER TABLE `PROC_BILLING_VALIDATION` ADD CONSTRAINT `PROC_BILV_OIT` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `PROC_BILV_OIT` ON `PROC_BILLING_VALIDATION`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `GIFT_CARD_FULFILLMENT` DROP FOREIGN KEY `GC_FILL_ODRI`;
ALTER TABLE `GIFT_CARD_FULFILLMENT` DROP INDEX `GC_FILL_ODRI`;
ALTER TABLE `GIFT_CARD_FULFILLMENT` ADD CONSTRAINT `GC_FILL_ODRI` FOREIGN KEY (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `GC_FILL_ODRI` ON `GIFT_CARD_FULFILLMENT`(`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);

ALTER TABLE `PRODUCT_ORDER_ITEM` DROP FOREIGN KEY `PROD_OITEM_ENOITM`;
ALTER TABLE `PRODUCT_ORDER_ITEM` DROP INDEX `PROD_OITEM_ENOITM`;
ALTER TABLE `PRODUCT_ORDER_ITEM` ADD CONSTRAINT `PROD_OITEM_ENOITM` FOREIGN KEY (`ENGAGEMENT_ID`, ENGAGEMENT_ITEM_SEQ_ID) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
--CREATE INDEX `PROD_OITEM_ENOITM` ON `PRODUCT_ORDER_ITEM`(`ENGAGEMENT_ID`, ENGAGEMENT_ITEM_SEQ_ID);

ALTER TABLE `PRODUCT_ORDER_ITEM` DROP FOREIGN KEY `PROD_OITEM_OITEM`;
ALTER TABLE `PRODUCT_ORDER_ITEM` DROP INDEX `PROD_OITEM_OITEM`;
ALTER TABLE `PRODUCT_ORDER_ITEM` ADD CONSTRAINT `PROD_OITEM_OITEM` FOREIGN KEY (`ORDER_ID`, ORDER_ITEM_SEQ_ID) REFERENCES `ORDER_ITEM` (`ORDER_ID`, `ORDER_ITEM_SEQ_ID`);
CREATE INDEX `PROD_OITEM_OITEM` ON `PRODUCT_ORDER_ITEM`(`ORDER_ID`, ORDER_ITEM_SEQ_ID);

ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP FOREIGN KEY `RIT_SHPMT_SHPMT`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP INDEX `RIT_SHPMT_SHPMT`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` ADD CONSTRAINT `RIT_SHPMT_SHPMT` FOREIGN KEY (`SHIPMENT_ID`) REFERENCES `SHIPMENT` (`SHIPMENT_ID`);
CREATE INDEX `RIT_SHPMT_SHPMT` ON `RETURN_ITEM_SHIPMENT`(`SHIPMENT_ID`);

ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP FOREIGN KEY `RIT_SHPMT_RITM`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP INDEX `RIT_SHPMT_RITM`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` ADD CONSTRAINT `RIT_SHPMT_RITM` FOREIGN KEY (`RETURN_ID`, `RETURN_ITEM_SEQ_ID`) REFERENCES `RETURN_ITEM` (`RETURN_ID`, `RETURN_ITEM_SEQ_ID`);
CREATE INDEX `RIT_SHPMT_RITM` ON `RETURN_ITEM_SHIPMENT`(`RETURN_ID`, `RETURN_ITEM_SEQ_ID`);

ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP FOREIGN KEY `RIT_SHPMT_RHDR`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` DROP INDEX `RIT_SHPMT_RHDR`;
ALTER TABLE `RETURN_ITEM_SHIPMENT` ADD CONSTRAINT `RIT_SHPMT_RHDR` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURN_HEADER` (`RETURN_ID`);
CREATE INDEX `RIT_SHPMT_RHDR` ON `RETURN_ITEM_SHIPMENT`(`RETURN_ID`);

ALTER TABLE `RETURN_ITEM_RESPONSE` DROP FOREIGN KEY `RTN_PAY_PAYMENT`;
ALTER TABLE `RETURN_ITEM_RESPONSE` DROP INDEX `RTN_PAY_PAYMENT`;
ALTER TABLE `RETURN_ITEM_RESPONSE` ADD CONSTRAINT `RTN_PAY_PAYMENT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT` (`PAYMENT_ID`);
--CREATE INDEX `RTN_PAY_PAYMENT` ON `RETURN_ITEM_RESPONSE`(`PAYMENT_ID`);

ALTER TABLE `RETURN_ITEM_RESPONSE` DROP FOREIGN KEY `RTN_PAY_FINACTTX`;
ALTER TABLE `RETURN_ITEM_RESPONSE` DROP INDEX `RTN_PAY_FINACTTX`;
ALTER TABLE `RETURN_ITEM_RESPONSE` ADD CONSTRAINT `RTN_PAY_FINACTTX` FOREIGN KEY (`FIN_ACCOUNT_TRANS_ID`) REFERENCES `FIN_ACCOUNT_TRANS` (`FIN_ACCOUNT_TRANS_ID`);
--CREATE INDEX `RTN_PAY_FINACTTX` ON `RETURN_ITEM_RESPONSE`(`FIN_ACCOUNT_TRANS_ID`);

ALTER TABLE `RETURN_ITEM_BILLING` DROP FOREIGN KEY `RTN_ITBLNG_RITM`;
ALTER TABLE `RETURN_ITEM_BILLING` DROP INDEX `RTN_ITBLNG_RITM`;
ALTER TABLE `RETURN_ITEM_BILLING` ADD CONSTRAINT `RTN_ITBLNG_RITM` FOREIGN KEY (`RETURN_ID`, `RETURN_ITEM_SEQ_ID`) REFERENCES `RETURN_ITEM` (`RETURN_ID`, `RETURN_ITEM_SEQ_ID`);
CREATE INDEX `RTN_ITBLNG_RITM` ON `RETURN_ITEM_BILLING`(`RETURN_ID`, `RETURN_ITEM_SEQ_ID`);

ALTER TABLE `RETURN_ITEM_BILLING` DROP FOREIGN KEY `RTN_ITBLNG_RHDR`;
ALTER TABLE `RETURN_ITEM_BILLING` DROP INDEX `RTN_ITBLNG_RHDR`;
ALTER TABLE `RETURN_ITEM_BILLING` ADD CONSTRAINT `RTN_ITBLNG_RHDR` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURN_HEADER` (`RETURN_ID`);
CREATE INDEX `RTN_ITBLNG_RHDR` ON `RETURN_ITEM_BILLING`(`RETURN_ID`);

ALTER TABLE `RETURN_ITEM_BILLING` DROP FOREIGN KEY `RETURN_ITBLNG_IITM`;
ALTER TABLE `RETURN_ITEM_BILLING` DROP INDEX `RETURN_ITBLNG_IITM`;
ALTER TABLE `RETURN_ITEM_BILLING` ADD CONSTRAINT `RETURN_ITBLNG_IITM` FOREIGN KEY (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`) REFERENCES `INVOICE_ITEM` (`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);
--CREATE INDEX `RETURN_ITBLNG_IITM` ON `RETURN_ITEM_BILLING`(`INVOICE_ID`, `INVOICE_ITEM_SEQ_ID`);

ALTER TABLE `RETURN_CONTACT_MECH` DROP FOREIGN KEY `RETURN_CMECH_HDR`;
ALTER TABLE `RETURN_CONTACT_MECH` DROP INDEX `RETURN_CMECH_HDR`;
ALTER TABLE `RETURN_CONTACT_MECH` ADD CONSTRAINT `RETURN_CMECH_HDR` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURN_HEADER` (`RETURN_ID`);
CREATE INDEX `RETURN_CMECH_HDR` ON `RETURN_CONTACT_MECH`(`RETURN_ID`);

ALTER TABLE `RETURN_ADJUSTMENT` DROP FOREIGN KEY `RETURN_ADJ_RHEAD`;
ALTER TABLE `RETURN_ADJUSTMENT` DROP INDEX `RETURN_ADJ_RHEAD`;
ALTER TABLE `RETURN_ADJUSTMENT` ADD CONSTRAINT `RETURN_ADJ_RHEAD` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURN_HEADER` (`RETURN_ID`);
--CREATE INDEX `RETURN_ADJ_RHEAD` ON `RETURN_ADJUSTMENT`(`RETURN_ID`);

ALTER TABLE `RETURN_ADJUSTMENT` DROP FOREIGN KEY `RETURN_ADJ_ORDADJ`;
ALTER TABLE `RETURN_ADJUSTMENT` DROP INDEX `RETURN_ADJ_ORDADJ`;
ALTER TABLE `RETURN_ADJUSTMENT` ADD CONSTRAINT `RETURN_ADJ_ORDADJ` FOREIGN KEY (`ORDER_ADJUSTMENT_ID`) REFERENCES `ORDER_ADJUSTMENT` (`ORDER_ADJUSTMENT_ID`);
--CREATE INDEX `RETURN_ADJ_ORDADJ` ON `RETURN_ADJUSTMENT`(`ORDER_ADJUSTMENT_ID`);

ALTER TABLE `PERF_REVIEW` DROP FOREIGN KEY `PERF_REV_PMNT`;
ALTER TABLE `PERF_REVIEW` DROP INDEX `PERF_REV_PMNT`;
ALTER TABLE `PERF_REVIEW` ADD CONSTRAINT `PERF_REV_PMNT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT` (`PAYMENT_ID`);
--CREATE INDEX `PERF_REV_PMNT` ON `PERF_REVIEW`(`PAYMENT_ID`);

ALTER TABLE `PERF_REVIEW` DROP FOREIGN KEY `PERF_REV_PMNT`;
ALTER TABLE `PERF_REVIEW` DROP INDEX `PERF_REV_PMNT`;
ALTER TABLE `PERF_REVIEW` ADD CONSTRAINT `PERF_REV_PMNT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT` (`PAYMENT_ID`);
CREATE INDEX `PERF_REV_PMNT` ON `PERF_REVIEW`(`PAYMENT_ID`);

ALTER TABLE `PAYMENT_BUDGET_ALLOCATION` DROP FOREIGN KEY `PAYMENT_BA_PMT`;
ALTER TABLE `PAYMENT_BUDGET_ALLOCATION` DROP INDEX `PAYMENT_BA_PMT`;
ALTER TABLE `PAYMENT_BUDGET_ALLOCATION` ADD CONSTRAINT `PAYMENT_BA_PMT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT` (`PAYMENT_ID`);
--CREATE INDEX `PAYMENT_BA_PMT` ON `PAYMENT_BUDGET_ALLOCATION`(`PAYMENT_ID`);

ALTER TABLE `DEDUCTION` DROP FOREIGN KEY `DEDCTN_PMNT`;
ALTER TABLE `DEDUCTION` DROP INDEX `DEDCTN_PMNT`;
ALTER TABLE `DEDUCTION` ADD CONSTRAINT `DEDCTN_PMNT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT` (`PAYMENT_ID`);
--CREATE INDEX `DEDCTN_PMNT` ON `DEDUCTION`(`PAYMENT_ID`);

ALTER TABLE `GL_RECONCILIATION_ENTRY` DROP FOREIGN KEY `GL_RECENT_ACTTXE`;
ALTER TABLE `GL_RECONCILIATION_ENTRY` DROP INDEX `GL_RECENT_ACTTXE`;
ALTER TABLE `GL_RECONCILIATION_ENTRY` ADD CONSTRAINT `GL_RECENT_ACTTXE` FOREIGN KEY (`ACCTG_TRANS_ID`, `ACCTG_TRANS_ENTRY_SEQ_ID`) REFERENCES `ACCTG_TRANS_ENTRY` (`ACCTG_TRANS_ID`, `ACCTG_TRANS_ENTRY_SEQ_ID`);
--CREATE INDEX `GL_RECENT_ACTTXE` ON `GL_RECONCILIATION_ENTRY`(`ACCTG_TRANS_ID`, `ACCTG_TRANS_ENTRY_SEQ_ID`);

ALTER TABLE `PICKLIST_ITEM` DROP FOREIGN KEY `PCKLST_ITM_OISG`;
ALTER TABLE `PICKLIST_ITEM` DROP INDEX `PCKLST_ITM_OISG`;
ALTER TABLE `PICKLIST_ITEM` ADD CONSTRAINT `PCKLST_ITM_OISG` FOREIGN KEY (`ORDER_ID`, `SHIP_GROUP_SEQ_ID`) REFERENCES `ORDER_ITEM_SHIP_GROUP` (`ORDER_ID`, `SHIP_GROUP_SEQ_ID`);
--CREATE INDEX `PCKLST_ITM_OISG` ON `PICKLIST_ITEM`(`ORDER_ID`, `SHIP_GROUP_SEQ_ID`);

ALTER TABLE `PICKLIST_BIN` DROP FOREIGN KEY `PCKLST_BIN_OISG`;
ALTER TABLE `PICKLIST_BIN` DROP INDEX `PCKLST_BIN_OISG`;
ALTER TABLE `PICKLIST_BIN` ADD CONSTRAINT `PCKLST_BIN_OISG` FOREIGN KEY (`PRIMARY_ORDER_ID`, `PRIMARY_SHIP_GROUP_SEQ_ID`) REFERENCES `ORDER_ITEM_SHIP_GROUP` (`ORDER_ID`, `SHIP_GROUP_SEQ_ID`);
--CREATE INDEX `PCKLST_BIN_OISG` ON `PICKLIST_BIN`(`PRIMARY_ORDER_ID`, `PRIMARY_SHIP_GROUP_SEQ_ID`);


ALTER TABLE `PRODUCT_SEARCH_RESULT` DROP FOREIGN KEY `PROD_SCHRES_VST`;
ALTER TABLE `PRODUCT_SEARCH_RESULT` DROP INDEX `PROD_SCHRES_VST`;
ALTER TABLE `PRODUCT_SEARCH_RESULT` ADD CONSTRAINT `PROD_SCHRES_VST` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
CREATE INDEX `PROD_SCHRES_VST` ON `PRODUCT_SEARCH_RESULT`(`VISIT_ID`);


ALTER TABLE `PRODUCT_KEYWORD_RESULT` DROP FOREIGN KEY `PROD_KWDRES_VST`;
ALTER TABLE `PRODUCT_KEYWORD_RESULT` DROP INDEX `PROD_KWDRES_VST`;
ALTER TABLE `PRODUCT_KEYWORD_RESULT` ADD CONSTRAINT `PROD_KWDRES_VST` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
--CREATE INDEX `PROD_KWDRES_VST` ON `PRODUCT_KEYWORD_RESULT`(`VISIT_ID`);

ALTER TABLE `PARTY_NEED` DROP FOREIGN KEY `PARTY_NEED_VSIT`;
ALTER TABLE `PARTY_NEED` DROP INDEX `PARTY_NEED_VSIT`;
ALTER TABLE `PARTY_NEED` ADD CONSTRAINT `PARTY_NEED_VSIT` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
--CREATE INDEX `PARTY_NEED_VSIT` ON `PARTY_NEED`(`VISIT_ID`);

ALTER TABLE `PARTY_DATA_SOURCE` DROP FOREIGN KEY `PARTY_DATSRC_VST`;
ALTER TABLE `PARTY_DATA_SOURCE` DROP INDEX `PARTY_DATSRC_VST`;
ALTER TABLE `PARTY_DATA_SOURCE` ADD CONSTRAINT `PARTY_DATSRC_VST` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
--CREATE INDEX `PARTY_DATSRC_VST` ON `PARTY_DATA_SOURCE`(`VISIT_ID`);

ALTER TABLE `INVENTORY_ITEM_TEMP_RES` DROP FOREIGN KEY `INV_ITEM_TR_VIS`;
ALTER TABLE `INVENTORY_ITEM_TEMP_RES` DROP INDEX `INV_ITEM_TR_VIS`;
ALTER TABLE `INVENTORY_ITEM_TEMP_RES` ADD CONSTRAINT `INV_ITEM_TR_VIS` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
CREATE INDEX `INV_ITEM_TR_VIS` ON `INVENTORY_ITEM_TEMP_RES`(`VISIT_ID`);

ALTER TABLE `CONTENT_SEARCH_RESULT` DROP FOREIGN KEY `CNT_SCHRES_VST`;
ALTER TABLE `CONTENT_SEARCH_RESULT` DROP INDEX `CNT_SCHRES_VST`;
ALTER TABLE `CONTENT_SEARCH_RESULT` ADD CONSTRAINT `CNT_SCHRES_VST` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
--CREATE INDEX `CNT_SCHRES_VST` ON `CONTENT_SEARCH_RESULT`(`VISIT_ID`);

ALTER TABLE `CART_ABANDONED_LINE` DROP FOREIGN KEY `CART_ABLN_VST`;
ALTER TABLE `CART_ABANDONED_LINE` DROP INDEX `CART_ABLN_VST`;
ALTER TABLE `CART_ABANDONED_LINE` ADD CONSTRAINT `CART_ABLN_VST` FOREIGN KEY (`VISIT_ID`) REFERENCES `VISIT` (`VISIT_ID`);
CREATE INDEX `CART_ABLN_VST` ON `CART_ABANDONED_LINE`(`VISIT_ID`);

ALTER TABLE `PRODUCT_SEARCH_CONSTRAINT` DROP FOREIGN KEY `PROD_SCHRSI_RES`;
ALTER TABLE `PRODUCT_SEARCH_CONSTRAINT` DROP INDEX `PROD_SCHRSI_RES`;
ALTER TABLE `PRODUCT_SEARCH_CONSTRAINT` ADD CONSTRAINT `PROD_SCHRSI_RES` FOREIGN KEY (`PRODUCT_SEARCH_RESULT_ID`) REFERENCES `PRODUCT_SEARCH_RESULT` (`PRODUCT_SEARCH_RESULT_ID`);
CREATE INDEX `PROD_SCHRSI_RES` ON `PRODUCT_SEARCH_CONSTRAINT`(`PRODUCT_SEARCH_RESULT_ID`);

ALTER TABLE `APPLICATION_SANDBOX` DROP FOREIGN KEY `APP_SNDBX_RNTMDTA`;
ALTER TABLE `APPLICATION_SANDBOX` DROP INDEX `APP_SNDBX_RNTMDTA`;
ALTER TABLE `APPLICATION_SANDBOX` ADD CONSTRAINT `APP_SNDBX_RNTMDTA` FOREIGN KEY (`RUNTIME_DATA_ID`) REFERENCES `RUNTIME_DATA` (`RUNTIME_DATA_ID`);
--CREATE INDEX `APP_SNDBX_RNTMDTA` ON `APPLICATION_SANDBOX`(`RUNTIME_DATA_ID`);








